WeaponList={"Shared","Zeus","Pistol","Heavy Pistol","Submachine Gun","Rifle","Shotgun","Scout","Auto Sniper","Sniper","Light Machine Gun"}

RF=gui.Reference

function NM(RFName,SetName)
    RFName:SetName(SetName)
end

NM(RF("Legitbot"),"合法")
    NM(RF("合法", "Aimbot"),"自瞄")
        NM(RF("合法", "自瞄", "Main"),"主要")
            NM(RF("合法", "自瞄", "主要", "Enable"),"自瞄总开关")
                RF("合法", "自瞄", "主要", "自瞄总开关"):SetDescription("启用自瞄")
            NM(RF("合法", "自瞄", "主要", "Aim Key"),"自瞄热键")
                RF("合法", "自瞄", "主要", "自瞄热键"):SetDescription("按住设定的热键时自瞄生效")
            NM(RF("合法", "自瞄", "主要", "Auto Pistol Interval"),"自动手枪间隔")
                RF("合法", "自瞄", "主要", "自动手枪间隔"):SetDescription("值不为0时, 长按开火键手枪连续开火, 开火间隔时间单位为毫秒")
        NM(RF("合法", "自瞄", "Hitbox Selection"),"自瞄部位选择")
            for i = 1, 11, 1 do
                NM(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Hitbox Advance Multiplier"),"自瞄部位切换速度")
                    RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "自瞄部位切换速度"):SetDescription("数值越大越快")
                NM(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Nearest To Crosshair"),"准星附近优先")
                    RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "准星附近优先"):SetDescription("自瞄首选准星最近部位")
            end
    NM(RF("合法", "Triggerbot"),"扳机")
        NM(RF("合法", "扳机", "Main"),"主要")
            NM(RF("合法", "扳机", "主要", "Enable"),"扳机总开关")
                RF("合法", "扳机", "主要", "扳机总开关"):SetDescription("启用扳机")
            NM(RF("合法", "扳机", "主要", "Trigger Key"),"扳机热键")
                RF("合法", "扳机", "主要", "扳机热键"):SetDescription("按住设定的热键时扳机生效")
            NM(RF("合法", "扳机", "主要", "Auto Fire"),"自动开火")
                RF("合法", "扳机", "主要", "自动开火"):SetDescription("启用时扳机常开, 不需要按住热键")
            NM(RF("合法", "扳机", "主要", "Knife Triggerbot"),"自动刀")
                RF("合法", "扳机", "主要", "自动刀"):SetDescription("未开启扳机总开关时, 启用此功能仍然生效")
        NM(RF("合法", "扳机", "Weapon"),"武器")
            for i = 1, 11, 1 do
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Delay"),"扳机延迟")
                    RF("合法", "扳机", "武器", WeaponList[i], "扳机延迟"):SetDescription("时间单位为毫秒")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Burst"),"扳机连发时间")
                    RF("合法", "扳机", "武器", WeaponList[i], "扳机连发时间"):SetDescription("时间单位为毫秒")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Hit Chance"),"最低命中率")
                    RF("合法", "扳机", "武器", WeaponList[i], "最低命中率"):SetDescription("超过最低命中率时才开火")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "Accuracy"),"强度提升")
                    RF("合法", "扳机", "武器", WeaponList[i], "强度提升"):SetDescription("启用后提高扳机强度")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "强度提升", "Anti-Recoil"),"反后坐")
                NM(RF("合法", "扳机", "武器", WeaponList[i], "强度提升", "Anti-Spread"),"反扩散")
            end
        NM(RF("合法", "扳机", "Hitboxes"),"部位")
    NM(RF("合法", "Weapon"),"武器")
        NM(RF("合法", "武器", "Accuracy"),"压枪")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器","压枪", WeaponList[i], "Recoil Control System"),"压枪时机")
                    RF("合法", "武器","压枪", WeaponList[i], "压枪时机"):SetDescription("抵消武器后坐力")
                    RF("合法", "武器","压枪", WeaponList[i], "压枪时机"):SetOptions("始终关闭","自瞄时","开火时")
                NM(RF("合法", "武器","压枪", WeaponList[i], "Horizontal Recoil"),"水平压枪")
                    RF("合法", "武器","压枪", WeaponList[i], "水平压枪"):SetDescription("将抵消多少水平后坐力")
                NM(RF("合法", "武器","压枪", WeaponList[i], "Vertical Recoil"),"垂直压枪")
                    RF("合法", "武器","压枪", WeaponList[i], "垂直压枪"):SetDescription("将抵消多少垂直后坐力")
            end
        NM(RF("合法", "武器", "Target"),"目标")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "目标", WeaponList[i], "Minimum FOV Range"),"最小范围")
                    RF("合法", "武器", "目标", WeaponList[i], "最小范围"):SetDescription("最小范围以内不自瞄")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Maximum FOV Range"),"最大范围")
                    RF("合法", "武器", "目标", WeaponList[i], "最大范围"):SetDescription("最大范围以外不自瞄")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Non-Sticky Target"),"超过范围不自瞄")
                    RF("合法", "武器", "目标", WeaponList[i], "超过范围不自瞄"):SetDescription("目标超出最大范围后即使未松开热键, 也停止自瞄")
                NM(RF("合法", "武器", "目标", WeaponList[i], "Target Switch Delay"),"目标切换延迟")
                    RF("合法", "武器", "目标", WeaponList[i], "目标切换延迟"):SetDescription("自瞄切换目标前的等待时间, 时间单位为毫秒")
                NM(RF("合法", "武器", "目标", WeaponList[i], "First Shot Delay"),"首次开火延迟")
                    RF("合法", "武器", "目标", WeaponList[i], "首次开火延迟"):SetDescription("自瞄射首发子弹前的等待时间, 时间单位为毫秒")
            end
        NM(RF("合法", "武器", "Aiming"),"瞄准")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Factor"),"平滑系数")
                    RF("合法", "武器", "瞄准", WeaponList[i], "平滑系数"):SetDescription("使自瞄更平滑, 越大越慢")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Method"),"平滑模式")
                    RF("合法", "武器", "瞄准", WeaponList[i], "平滑模式"):SetDescription("用于自瞄的平滑方法")
                    RF("合法", "武器", "瞄准", WeaponList[i], "平滑模式"):SetOptions("动态", "静态")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Randomize Factor"),"随机因子")
                    RF("合法", "武器", "瞄准", WeaponList[i], "随机因子"):SetDescription("增加自瞄的随机性, 使其更像人类操作")
                NM(RF("合法", "武器", "瞄准", WeaponList[i], "Curve Factor"),"曲线因子")
                    RF("合法", "武器", "瞄准", WeaponList[i], "曲线因子"):SetDescription("自瞄的非线性程度")
            end
        NM(RF("合法", "武器", "Visibility"),"可见性")
            for i = 1, 11, 1 do
                NM(RF("合法", "武器", "可见性", WeaponList[i], "Auto Wall"),"穿墙")
                    RF("合法", "武器", "可见性", WeaponList[i], "穿墙"):SetDescription("自瞄与扳机穿可穿透的墙")
                NM(RF("合法", "武器", "可见性", WeaponList[i], "Through Smoke"),"穿烟")
                    RF("合法", "武器", "可见性", WeaponList[i], "穿烟"):SetDescription("自瞄与扳机穿烟")
            end

NM(RF("Ragebot"),"暴力")
    NM(RF("暴力", "Main"),"主要")
        NM(RF("暴力", "主要", "Enabled"),"自瞄总开关")
            RF("暴力", "主要", "自瞄总开关"):SetDescription("启用暴力自瞄")
        NM(RF("暴力", "主要", "Silent Aim"),"静默")
            RF("暴力", "主要", "静默"):SetDescription("自瞄不会更改你的视角")
        NM(RF("暴力", "主要", "Backtrack"),"回溯")
            RF("暴力", "主要", "回溯"):SetDescription("自瞄击中敌人之前的位置也造成伤害")
        NM(RF("暴力", "主要", "Anti-Recoil"),"无后坐")
            RF("暴力", "主要", "无后坐"):SetDescription("抵消武器后坐")
        NM(RF("暴力", "主要", "Anti-Spread"),"无扩散")
            RF("暴力", "主要", "无扩散"):SetDescription("抵消武器扩散 [需关安全模式]")
        NM(RF("暴力", "主要", "Target Selection"),"目标优先级")
            RF("暴力", "主要", "目标优先级"):SetDescription("自瞄优先选择目标")
            RF("暴力", "主要", "目标优先级"):SetOptions("最低血量", "距离最近", "离准星最近")
        NM(RF("暴力", "主要", "FOV"),"范围")
            RF("暴力", "主要", "范围"):SetDescription("自瞄的最大范围")
        NM(RF("暴力", "主要", "Knifebot"),"自动刀")
            RF("暴力", "主要", "自动刀"):SetDescription("选择目标在范围内自动刀人的模式")
            RF("暴力", "主要", "自动刀"):SetOptions("关闭","默认","仅背刺","快速")
        NM(RF("暴力", "主要", "Duck Peek assist"),"蹲起Peek")
            RF("暴力", "主要", "蹲起Peek"):SetDescription("蹲下时如果站起可对目标造成伤害, 则自动站起")
    NM(RF("暴力", "Anti-Aim"),"反自瞄")
        NM(RF("暴力", "反自瞄", "Enabled"),"反自瞄总开关")
            RF("暴力", "反自瞄", "反自瞄总开关"):SetDescription("启用反自瞄")
        NM(RF("暴力", "反自瞄", "Pitch Angle"),"俯仰角度")
            RF("暴力", "反自瞄", "俯仰角度"):SetDescription("反自瞄的俯仰角度选项")
            RF("暴力", "反自瞄", "俯仰角度"):SetOptions("关闭","低头","抬头","假抬头","平视")
        NM(RF("暴力", "反自瞄", "Yaw Angle"),"偏航角度")
            RF("暴力", "反自瞄", "偏航角度"):SetDescription("反自瞄的偏航角度选项")
            RF("暴力", "反自瞄", "偏航角度"):SetOptions("朝前","朝后")
        NM(RF("暴力", "反自瞄", "Auto Direction"),"自动朝向")
            RF("暴力", "反自瞄", "自动朝向"):SetDescription("反自瞄自动朝向选项")
            NM(RF("暴力", "反自瞄", "自动朝向", "At Edges"),"墙边藏头")
            NM(RF("暴力", "反自瞄", "自动朝向", "At Targets"),"朝向目标")
        NM(RF("暴力", "反自瞄", "Disable Conditions"),"禁用条件")
            RF("暴力", "反自瞄", "禁用条件"):SetDescription("选择反自瞄在什么情况下禁用")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Use"),"交互时")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Knife"),"持刀时")
            NM(RF("暴力", "反自瞄", "禁用条件", "On Grenade"),"持道具时")
            NM(RF("暴力", "反自瞄", "禁用条件", "During Freeze Time"),"回合冻结时")
    NM(RF("暴力", "Auto Peek"),"自动Peek")
        NM(RF("暴力", "自动Peek", "Enable"),"自动Peek总开关")
            RF("暴力", "自动Peek", "自动Peek总开关"):SetDescription("启用自动Peek")
        NM(RF("暴力", "自动Peek", "Key"),"自动Peek热键")
            RF("暴力", "自动Peek", "自动Peek热键"):SetDescription("按住设定的热键时自动Peek生效")
        NM(RF("暴力", "自动Peek", "Show indicator"),"渲染指示器")
            RF("暴力", "自动Peek", "渲染指示器"):SetDescription("在脚底渲染指示器")
        NM(RF("暴力", "自动Peek", "Type"),"热键模式")
            RF("暴力", "自动Peek", "热键模式"):SetDescription("选择热键的工作模式")
            RF("暴力", "自动Peek", "热键模式"):SetOptions("按住","切换")
        NM(RF("暴力", "自动Peek", "Maintain Origin"),"复位后不移除指示器")
            RF("暴力", "自动Peek", "复位后不移除指示器"):SetDescription("开启此选项后, 复位不移除指示器, 可再次Peek")
    NM(RF("暴力", "Accuracy"),"数值")
        for i = 1, 11, 1 do
            NM(RF("暴力", "数值", WeaponList[i], "Min Damage"),"最低伤害")
                RF("暴力", "数值", WeaponList[i], "最低伤害"):SetDescription("自瞄开火的最低伤害阈值")
            NM(RF("暴力", "数值", WeaponList[i], "Min Damage Options"),"其它选项")
            NM(RF("暴力", "数值", WeaponList[i], "其它选项", "Auto Wall"),"穿墙")
            NM(RF("暴力", "数值", WeaponList[i], "其它选项", "Adaptive Damage"),"自适应伤害")
            NM(RF("暴力", "数值", WeaponList[i], "Hit Chance"),"最低命中率")
                RF("暴力", "数值", WeaponList[i], "最低命中率"):SetDescription("超过最低命中率时才开火")
        end
    NM(RF("暴力", "Hitbox"),"部位")
        for i = 1, 11, 1 do
            NM(RF("暴力", "部位", WeaponList[i], "Head"),"头部")
                RF("暴力", "部位", WeaponList[i], "头部"):SetDescription("配置头部选项")
            NM(RF("暴力", "部位", WeaponList[i], "头部", "Priority"),"优先")
            NM(RF("暴力", "部位", WeaponList[i], "头部", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "头部", "Center"),"中心")
            NM(RF("暴力", "部位", WeaponList[i], "Body"),"身体")
                RF("暴力", "部位", WeaponList[i], "身体"):SetDescription("配置身体选项")
            NM(RF("暴力", "部位", WeaponList[i], "身体", "Priority"),"优先")
            NM(RF("暴力", "部位", WeaponList[i], "身体", "Lethal"),"致命")
            NM(RF("暴力", "部位", WeaponList[i], "身体", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "身体", "Center"),"中心")
            NM(RF("暴力", "部位", WeaponList[i], "Limbs"),"四肢")
                RF("暴力", "部位", WeaponList[i], "四肢"):SetDescription("配置四肢选项")
            NM(RF("暴力", "部位", WeaponList[i], "四肢", "Exposed"),"暴露")
            NM(RF("暴力", "部位", WeaponList[i], "四肢", "Center"),"中心")
        end
    NM(RF("暴力", "Automate"),"自动")
        -- All Weapon [Auto Stop]
        for i = 1, 11, 1 do
            NM(RF("暴力", "自动", WeaponList[i], "Auto Stop"),"提高命中率")
                RF("暴力", "自动", WeaponList[i], "提高命中率"):SetDescription("自动操作以提高命中率")
                NM(RF("暴力", "自动", WeaponList[i], "提高命中率", "Stop"),"自动急停")
                NM(RF("暴力", "自动", WeaponList[i], "提高命中率", "Slow Walk"),"自动慢走")
                NM(RF("暴力", "自动", WeaponList[i], "提高命中率", "Duck"),"射击前蹲下")
                NM(RF("暴力", "自动", WeaponList[i], "提高命中率", "Early"),"提前急停")
                NM(RF("暴力", "自动", WeaponList[i], "提高命中率", "Between Shots"),"开火间隙急停")
        end
        -- Shared
        NM(RF("暴力", "自动", "Shared", "Auto Fire"),"开火选项")
            RF("暴力", "自动", "Shared", "开火选项"):SetDescription("手枪的自动选项")
            NM(RF("暴力", "自动", "Shared", "开火选项", "Auto Pistol"),"自动手枪")
            NM(RF("暴力", "自动", "Shared", "开火选项", "Auto Revolver"),"R8自动预热")
        NM(RF("暴力", "自动", "Shared", "Auto Scope"),"开关镜")
            RF("暴力", "自动", "Shared", "开关镜"):SetDescription("狙击枪的自动选项")
            NM(RF("暴力", "自动", "Shared", "开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Shared", "开关镜", "Unscope"),"自动关镜")
        -- Pistol
        NM(RF("暴力", "自动", "Pistol", "Auto Fire"),"开火选项")
            RF("暴力", "自动", "Pistol", "开火选项"):SetDescription("手枪的自动选项")
            NM(RF("暴力", "自动", "Pistol", "开火选项", "Auto Pistol"),"自动手枪")
        -- Heavy Pistol
        NM(RF("暴力", "自动", "Heavy Pistol", "Auto Fire"),"开火选项")
            RF("暴力", "自动", "Heavy Pistol", "开火选项"):SetDescription("手枪的自动选项")
            NM(RF("暴力", "自动", "Heavy Pistol", "开火选项", "Auto Pistol"),"自动手枪")
            NM(RF("暴力", "自动", "Heavy Pistol", "开火选项", "Auto Revolver"),"R8自动预热")
        -- Scout
        NM(RF("暴力", "自动", "Scout", "Auto Fire"),"开火选项")
            RF("暴力", "自动", "Scout", "开火选项"):SetDescription("手枪的自动选项")
            NM(RF("暴力", "自动", "Scout", "开火选项", "Auto Pistol"),"自动手枪")
        NM(RF("暴力", "自动", "Scout", "Auto Scope"),"开关镜")
            RF("暴力", "自动", "Scout", "开关镜"):SetDescription("狙击枪的自动选项")
            NM(RF("暴力", "自动", "Scout", "开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Scout", "开关镜", "Unscope"),"自动关镜")
        -- Auto Sniper
        NM(RF("暴力", "自动", "Auto Sniper", "Auto Scope"),"开关镜")
            RF("暴力", "自动", "Auto Sniper", "开关镜"):SetDescription("狙击枪的自动选项")
            NM(RF("暴力", "自动", "Auto Sniper", "开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Auto Sniper", "开关镜", "Unscope"),"自动关镜")
        -- Sniper
        NM(RF("暴力", "自动", "Sniper", "Auto Fire"),"开火选项")
            RF("暴力", "自动", "Sniper", "开火选项"):SetDescription("手枪的自动选项")
            NM(RF("暴力", "自动", "Sniper", "开火选项", "Auto Pistol"),"自动手枪")
        NM(RF("暴力", "自动", "Sniper", "Auto Scope"),"开关镜")
            RF("暴力", "自动", "Sniper", "开关镜"):SetDescription("狙击枪的自动选项")
            NM(RF("暴力", "自动", "Sniper", "开关镜", "Scope"),"自动开镜")
            NM(RF("暴力", "自动", "Sniper", "开关镜", "Unscope"),"自动关镜")

NM(RF("Visuals"),"视觉")
    NM(RF("视觉", "Enemy"),"敌人")
        NM(RF("视觉", "敌人", "Overlay"),"预览")
            NM(RF("视觉", "敌人", "预览", "Box"),"方框")
                NM(RF("视觉", "敌人", "预览", "方框", "Style"),"样式")
                    RF("视觉", "敌人", "预览", "方框", "样式"):SetOptions("粗线","细线")
                NM(RF("视觉", "敌人", "预览", "方框", "Precision"),"精确模式")
                NM(RF("视觉", "敌人", "预览", "方框", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Ammo"),"弹药")
                NM(RF("视觉", "敌人", "预览", "弹药", "Ammo Full Color"),"满弹药颜色")
                NM(RF("视觉", "敌人", "预览", "弹药", "Ammo Empty Color"),"空弹药颜色")
            NM(RF("视觉", "敌人", "预览", "Health"),"生命")
                NM(RF("视觉", "敌人", "预览", "生命", "Health Bar"),"生命条")
                    NM(RF("视觉", "敌人", "预览", "生命", "生命条", "Health Max Color"),"满生命颜色")
                    NM(RF("视觉", "敌人", "预览", "生命", "生命条", "Health Low Color"),"低生命颜色")
                NM(RF("视觉", "敌人", "预览", "生命", "Health Number"),"生命数值")
            NM(RF("视觉", "敌人", "预览", "Name"),"名字")
                NM(RF("视觉", "敌人", "预览", "名字", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Skeleton"),"骨骼")
                NM(RF("视觉", "敌人", "预览", "骨骼", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Armor"),"护甲")
                NM(RF("视觉", "敌人", "预览", "护甲", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Money"),"金钱")
                NM(RF("视觉", "敌人", "预览", "金钱", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Ping"),"延迟")
                NM(RF("视觉", "敌人", "预览", "延迟", "Color"),"颜色")
            NM(RF("视觉", "敌人", "预览", "Flags"),"标志")
                NM(RF("视觉", "敌人", "预览", "标志", "Defusing"),"拆弹中")
                NM(RF("视觉", "敌人", "预览", "标志", "Planting"),"安包中")
                NM(RF("视觉", "敌人", "预览", "标志", "Scoped"),"开镜中")
                NM(RF("视觉", "敌人", "预览", "标志", "Reloading"),"换弹中")
                NM(RF("视觉", "敌人", "预览", "标志", "Pin Pulled"),"已拉环")
                NM(RF("视觉", "敌人", "预览", "标志", "Flashed"),"被闪中")
                NM(RF("视觉", "敌人", "预览", "标志", "Has Defuser"),"有钳子")
                NM(RF("视觉", "敌人", "预览", "标志", "Has C4"),"带包")
            NM(RF("视觉", "敌人", "预览", "Barrel"),"枪口")
                NM(RF("视觉", "敌人", "预览", "枪口", "Start"),"起始渐变色")
                NM(RF("视觉", "敌人", "预览", "枪口", "End"),"结束渐变色")
            NM(RF("视觉", "敌人", "预览", "Weapon"),"武器")
                NM(RF("视觉", "敌人", "预览", "武器", "Style"),"样式")
                    RF("视觉", "敌人", "预览", "武器", "样式"):SetOptions("图标","名称")
                NM(RF("视觉", "敌人", "预览", "武器", "Filter"),"过滤")
                    NM(RF("视觉", "敌人", "预览", "武器", "过滤", "Active"),"手持")
                    NM(RF("视觉", "敌人", "预览", "武器", "过滤", "Inventory"),"背包")
                    NM(RF("视觉", "敌人", "预览", "武器", "过滤", "Nades"),"投掷物")
                NM(RF("视觉", "敌人", "预览", "武器", "Color"),"颜色")
                NM(RF("视觉", "敌人", "预览", "武器", "Important Color"),"重要信息颜色")
        NM(RF("视觉", "敌人", "Chams"),"上色")
            NM(RF("视觉", "敌人", "上色", "Model Visible"),"可见模型")
                RF("视觉", "敌人", "上色", "可见模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "敌人", "上色", "Model Occluded"),"被遮挡模型")
                RF("视觉", "敌人", "上色", "被遮挡模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "敌人", "上色", "Model Glow"),"模型边缘发光")
                RF("视觉", "敌人", "上色", "模型边缘发光"):SetOptions("关闭","开启")
            NM(RF("视觉", "敌人", "上色", "Attachments Visible"),"可见武器")
                RF("视觉", "敌人", "上色", "可见武器"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "敌人", "上色", "Attachments Occluded"),"被遮挡武器")
                RF("视觉", "敌人", "上色", "被遮挡武器"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "敌人", "上色", "Ragdoll Visible"),"可见尸体")
                RF("视觉", "敌人", "上色", "可见尸体"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "敌人", "上色", "Ragdoll Occluded"),"被遮挡尸体")
                RF("视觉", "敌人", "上色", "被遮挡尸体"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
    NM(RF("视觉", "Team"),"队友")
        NM(RF("视觉", "队友", "Overlay"),"预览")
            NM(RF("视觉", "队友", "预览", "Box"),"方框")
                NM(RF("视觉", "队友", "预览", "方框", "Style"),"样式")
                    RF("视觉", "队友", "预览", "方框", "样式"):SetOptions("粗线","细线")
                NM(RF("视觉", "队友", "预览", "方框", "Precision"),"精确模式")
                NM(RF("视觉", "队友", "预览", "方框", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Ammo"),"弹药")
                NM(RF("视觉", "队友", "预览", "弹药", "Ammo Full Color"),"满弹药颜色")
                NM(RF("视觉", "队友", "预览", "弹药", "Ammo Empty Color"),"空弹药颜色")
            NM(RF("视觉", "队友", "预览", "Health"),"生命")
                NM(RF("视觉", "队友", "预览", "生命", "Health Bar"),"生命条")
                    NM(RF("视觉", "队友", "预览", "生命", "生命条", "Health Max Color"),"满生命颜色")
                    NM(RF("视觉", "队友", "预览", "生命", "生命条", "Health Low Color"),"低生命颜色")
                NM(RF("视觉", "队友", "预览", "生命", "Health Number"),"生命数值")
            NM(RF("视觉", "队友", "预览", "Name"),"名字")
                NM(RF("视觉", "队友", "预览", "名字", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Skeleton"),"骨骼")
                NM(RF("视觉", "队友", "预览", "骨骼", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Armor"),"护甲")
                NM(RF("视觉", "队友", "预览", "护甲", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Money"),"金钱")
                NM(RF("视觉", "队友", "预览", "金钱", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Ping"),"延迟")
                NM(RF("视觉", "队友", "预览", "延迟", "Color"),"颜色")
            NM(RF("视觉", "队友", "预览", "Flags"),"标志")
                NM(RF("视觉", "队友", "预览", "标志", "Defusing"),"拆弹中")
                NM(RF("视觉", "队友", "预览", "标志", "Planting"),"安包中")
                NM(RF("视觉", "队友", "预览", "标志", "Scoped"),"开镜中")
                NM(RF("视觉", "队友", "预览", "标志", "Reloading"),"换弹中")
                NM(RF("视觉", "队友", "预览", "标志", "Pin Pulled"),"已拉环")
                NM(RF("视觉", "队友", "预览", "标志", "Flashed"),"被闪中")
                NM(RF("视觉", "队友", "预览", "标志", "Has Defuser"),"有钳子")
                NM(RF("视觉", "队友", "预览", "标志", "Has C4"),"带包")
            NM(RF("视觉", "队友", "预览", "Barrel"),"枪口")
                NM(RF("视觉", "队友", "预览", "枪口", "Start"),"起始渐变色")
                NM(RF("视觉", "队友", "预览", "枪口", "End"),"结束渐变色")
            NM(RF("视觉", "队友", "预览", "Weapon"),"武器")
                NM(RF("视觉", "队友", "预览", "武器", "Style"),"样式")
                    RF("视觉", "队友", "预览", "武器", "样式"):SetOptions("图标","名称")
                NM(RF("视觉", "队友", "预览", "武器", "Filter"),"过滤")
                    NM(RF("视觉", "队友", "预览", "武器", "过滤", "Active"),"手持")
                    NM(RF("视觉", "队友", "预览", "武器", "过滤", "Inventory"),"背包")
                    NM(RF("视觉", "队友", "预览", "武器", "过滤", "Nades"),"投掷物")
                NM(RF("视觉", "队友", "预览", "武器", "Color"),"颜色")
                NM(RF("视觉", "队友", "预览", "武器", "Important Color"),"重要信息颜色")
        NM(RF("视觉", "队友", "Chams"),"上色")
            NM(RF("视觉", "队友", "上色", "Model Visible"),"可见模型")
                RF("视觉", "队友", "上色", "可见模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "队友", "上色", "Model Occluded"),"被遮挡模型")
                RF("视觉", "队友", "上色", "被遮挡模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "队友", "上色", "Model Glow"),"模型边缘发光")
                RF("视觉", "队友", "上色", "模型边缘发光"):SetOptions("关闭","开启")
            NM(RF("视觉", "队友", "上色", "Attachments Visible"),"可见武器")
                RF("视觉", "队友", "上色", "可见武器"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "队友", "上色", "Attachments Occluded"),"被遮挡武器")
                RF("视觉", "队友", "上色", "被遮挡武器"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "队友", "上色", "Ragdoll Visible"),"可见尸体")
                RF("视觉", "队友", "上色", "可见尸体"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "队友", "上色", "Ragdoll Occluded"),"被遮挡尸体")
                RF("视觉", "队友", "上色", "被遮挡尸体"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
    NM(RF("视觉", "Weapon"),"武器")
        NM(RF("视觉", "武器", "Overlay"),"预览")
            NM(RF("视觉", "武器", "预览", "Box"),"方框")
                NM(RF("视觉", "武器", "预览", "方框", "Style"),"样式")
                    RF("视觉", "武器", "预览", "方框", "样式"):SetOptions("粗线","细线")
                NM(RF("视觉", "武器", "预览", "方框", "Precision"),"精确模式")
                NM(RF("视觉", "武器", "预览", "方框", "Color"),"颜色")
            NM(RF("视觉", "武器", "预览", "Ammo"),"弹药")
                NM(RF("视觉", "武器", "预览", "弹药", "Ammo Full Color"),"满弹药颜色")
                NM(RF("视觉", "武器", "预览", "弹药", "Ammo Empty Color"),"空弹药颜色")
            NM(RF("视觉", "武器", "预览", "Name"),"名字")
                NM(RF("视觉", "武器", "预览", "名字", "Style"),"样式")
                    RF("视觉", "武器", "预览", "名字", "样式"):SetOptions("图标","名称")
                NM(RF("视觉", "武器", "预览", "名字", "Color"),"颜色")
            NM(RF("视觉", "武器", "预览", "Nades"),"投掷物")
                NM(RF("视觉", "武器", "预览", "投掷物", "Name"),"名称")
                NM(RF("视觉", "武器", "预览", "投掷物", "Icon"),"图标")
                NM(RF("视觉", "武器", "预览", "投掷物", "Detonate Timer"),"引爆计时器")
            NM(RF("视觉", "武器", "预览", "C4 Timer"),"C4计时")
            NM(RF("视觉", "武器", "预览", "Defuser"),"钳子")
        NM(RF("视觉", "武器", "Chams"),"上色")
            NM(RF("视觉", "武器", "上色", "Model Visible"),"可见模型")
                RF("视觉", "武器", "上色", "可见模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "武器", "上色", "Model Occluded"),"被遮挡模型")
                RF("视觉", "武器", "上色", "被遮挡模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "武器", "上色", "Model Glow"),"模型发光")
                RF("视觉", "武器", "上色", "模型发光"):SetOptions("关闭","开启")
    NM(RF("视觉", "Local"),"自身")
        NM(RF("视觉", "自身", "Chams"),"上色")
            NM(RF("视觉", "自身", "上色", "Model Visible"),"可见模型")
                RF("视觉", "自身", "上色", "可见模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "自身", "上色", "Model Occluded"),"被遮挡模型")
                RF("视觉", "自身", "上色", "被遮挡模型"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "自身", "上色", "Attachments Visible"),"可见武器(第三人称)")
                RF("视觉", "自身", "上色", "可见武器(第三人称)"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "自身", "上色", "Attachments Occluded"),"被遮挡武器(第三人称)")
                RF("视觉", "自身", "上色", "被遮挡武器(第三人称)"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "自身", "上色", "Weapon Visible"),"可见武器(第一人称)")
                RF("视觉", "自身", "上色", "可见武器(第一人称)"):SetOptions("关闭","平面","纹理","发光","塑料","金属")
            NM(RF("视觉", "自身", "上色", "Arms Visible"),"可见手臂(第一人称)")
                RF("视觉", "自身", "上色", "可见手臂(第一人称)"):SetOptions("关闭","平面","纹理","发光","塑料","金属")

NM(RF("World"),"世界")
    NM(RF("世界", "Camera"),"相机")
        NM(RF("世界", "相机", "Third Person Enable"),"第三人称开关")
            RF("世界", "相机", "第三人称开关"):SetDescription("启用第三人称视角")
        NM(RF("世界", "相机", "Third Person Distance"),"第三人称距离")
            RF("世界", "相机", "第三人称距离"):SetDescription("第三人称视角距离")
        NM(RF("世界", "相机", "View FOV"),"视野范围")
            RF("世界", "相机", "视野范围"):SetDescription("调整整体视野范围")
        NM(RF("世界", "相机", "Viewmodel FOV"),"模型范围")
            RF("世界", "相机", "模型范围"):SetDescription("调整武器模型视野范围")
    NM(RF("世界", "Extra"),"额外")
        NM(RF("世界", "额外", "Radar"),"地图雷达")
            RF("世界", "额外", "地图雷达"):SetDescription("游戏地图显示敌人位置")
        NM(RF("世界", "额外", "Visualize Aimbot"),"渲染解析点")
            RF("世界", "额外", "渲染解析点"):SetDescription("Peek时渲染解析点")
        NM(RF("世界", "额外", "Crosshair"),"准星")
            RF("世界", "额外", "准星"):SetDescription("显示准星")
        NM(RF("世界", "额外", "Crosshair Recoil"),"可视扩散")
            RF("世界", "额外", "可视扩散"):SetDescription("渲染扩散范围")
            RF("世界", "额外", "可视扩散"):SetOptions("关闭","圆环","渐变","圆环[仅暴力]")
    NM(RF("世界", "Effects"),"特效")
        NM(RF("世界", "特效", "Effects Removal"),"特效移除")
            RF("世界", "特效", "特效移除"):SetDescription("移除视觉特效")
            NM(RF("世界", "特效", "特效移除", "No Flash"),"闪光")
            NM(RF("世界", "特效", "特效移除", "No Smoke"),"烟雾")
            NM(RF("世界", "特效", "特效移除", "No Recoil"),"视觉后坐")
            NM(RF("世界", "特效", "特效移除", "No Scope"),"瞄准镜放大")
            NM(RF("世界", "特效", "特效移除", "No Scope Overlay"),"瞄准镜虚化")
            NM(RF("世界", "特效", "特效移除", "No Sky"),"天空")
        NM(RF("世界", "特效", "Night Mode"),"夜间模式")
            RF("世界", "特效", "夜间模式"):SetDescription("降低亮度")
        NM(RF("世界", "特效", "Night Mode Intensity"),"夜间模式亮度")
            RF("世界", "特效", "夜间模式亮度"):SetDescription("0不生效, 1为最亮")
    NM(RF("世界", "Helper"),"辅助")
        NM(RF("世界", "辅助", "Wallbang Info"),"穿墙指示器")
            RF("世界", "辅助", "穿墙指示器"):SetDescription("显示穿墙伤害信息")
            NM(RF("世界", "辅助", "穿墙指示器", "Damage"),"伤害")
            NM(RF("世界", "辅助", "穿墙指示器", "Circle"),"圆圈")
            NM(RF("世界", "辅助", "穿墙指示器", "Crosshair"),"准星")
        NM(RF("世界", "辅助", "Out Of View"),"视野外指示器")
            RF("世界", "辅助", "视野外指示器"):SetDescription("显示视野外敌人方位")
            RF("世界", "辅助", "视野外指示器"):SetOptions("关闭","箭头","箭头+信息")
        NM(RF("世界", "辅助", "Out Of View Scale"),"视野外指示器离准星距离")
            RF("世界", "辅助", "视野外指示器离准星距离"):SetDescription("调整指示器离准星的距离")
        NM(RF("世界", "辅助", "Inferno"),"显示燃烧弹范围")
            RF("世界", "辅助", "显示燃烧弹范围"):SetDescription("燃烧弹蔓延范围")
            NM(RF("世界", "辅助", "显示燃烧弹范围", "Local"),"自身")
            NM(RF("世界", "辅助", "显示燃烧弹范围", "Friendly"),"友军")
            NM(RF("世界", "辅助", "显示燃烧弹范围", "Enemy"),"敌人")
        NM(RF("世界", "辅助", "Smoke"),"显示烟雾范围")
            RF("世界", "辅助", "显示烟雾范围"):SetDescription("烟雾蔓延范围")
        NM(RF("世界", "辅助", "Grenade Tracer"),"显示手雷轨迹")
            RF("世界", "辅助", "显示手雷轨迹"):SetDescription("手雷空中轨迹")
            NM(RF("世界", "辅助", "显示手雷轨迹", "Local"),"自身")
            NM(RF("世界", "辅助", "显示手雷轨迹", "Friendly"),"友军")
            NM(RF("世界", "辅助", "显示手雷轨迹", "Enemy"),"敌人")
            NM(RF("世界", "辅助", "显示手雷轨迹", "Color Fade"),"颜色渐变")
        NM(RF("世界", "辅助", "Grenade Warning"),"显示手雷警告")
            RF("世界", "辅助", "显示手雷警告"):SetDescription("手雷落点警告")
            NM(RF("世界", "辅助", "显示手雷警告", "Local"),"自身")
            NM(RF("世界", "辅助", "显示手雷警告", "Friendly"),"友军")
            NM(RF("世界", "辅助", "显示手雷警告", "Enemy"),"敌人")
        NM(RF("世界", "辅助", "Hit Effects"),"显示命中特效")
            RF("世界", "辅助", "显示命中特效"):SetDescription("命中敌人时的特效")
            NM(RF("世界", "辅助", "显示命中特效", "Sound"),"声音")
            NM(RF("世界", "辅助", "显示命中特效", "Marker"),"标记")
        NM(RF("世界", "辅助", "Damage Indicator"),"伤害指示器开关")
            RF("世界", "辅助", "伤害指示器开关"):SetDescription("命中后在敌人头顶渲染伤害值")
        NM(RF("世界", "辅助", "Bullet Tracers"),"显示子弹轨迹")
            RF("世界", "辅助", "显示子弹轨迹"):SetDescription("渲染子弹飞行轨迹")
            NM(RF("世界", "辅助", "显示子弹轨迹", "Local"),"自身")
            NM(RF("世界", "辅助", "显示子弹轨迹", "Friendly"),"友军")
            NM(RF("世界", "辅助", "显示子弹轨迹", "Enemy"),"敌人")

NM(RF("Miscellaneous"),"杂项")
    NM(RF("杂项", "Features"),"功能")
        NM(RF("杂项", "功能", "Secure Mode"),"安全模式")
            RF("杂项", "功能", "安全模式"):SetDescription("禁用不安全的功能, 降低封禁概率")
            RF("杂项", "功能", "安全模式"):SetOptions("严格","开启","关闭");
        NM(RF("杂项", "功能", "Chat Spam"),"广告")
            RF("杂项", "功能", "广告"):SetDescription("自动发送AW广告消息")
        NM(RF("杂项", "功能", "Auto-Accept Match"),"自动准备")
            RF("杂项", "功能", "自动准备"):SetDescription("自动最后一个准备比赛")
        NM(RF("杂项", "功能", "Preserve Killfeed"),"保留击杀信息")
            RF("杂项", "功能", "保留击杀信息"):SetDescription("不移除击杀信息")
        NM(RF("杂项", "功能", "Show Spectators"),"显示观战者")
            RF("杂项", "功能", "显示观战者"):SetDescription("显示观战你的玩家")
        NM(RF("杂项", "功能", "Anti-OBS"),"反OBS")
            RF("杂项", "功能", "反OBS"):SetDescription("使OBS录不到作弊画面, 只支持OBS的游戏采集")
        NM(RF("杂项", "功能", "Show Watermark"),"显示水印")
            RF("杂项", "功能", "显示水印"):SetDescription("右上角显示水印")
        NM(RF("杂项", "功能", "Quick Plant"),"禁用快速下包")
            RF("杂项", "功能", "禁用快速下包"):SetDescription("应该是自动快速下包的, 等修复")
        NM(RF("杂项", "功能", "Log"),"日志")
            RF("杂项", "功能", "日志"):SetDescription("左上角显示日志信息")
            NM(RF("杂项", "功能", "日志", "Console"),"控制台")
            NM(RF("杂项", "功能", "日志", "Purchases"),"购买")
            NM(RF("杂项", "功能", "日志", "Damage"),"伤害")
    NM(RF("杂项", "Movement"),"移动")
        NM(RF("杂项", "移动", "Auto Strafe"),"空中加速")
            RF("杂项", "移动", "空中加速"):SetDescription("抖头, 不适合绿演")
        NM(RF("杂项", "移动", "Auto Jump"),"连跳")
            RF("杂项", "移动", "连跳"):SetDescription("选择自动连跳的模式")
            RF("杂项", "移动", "连跳"):SetOptions("关闭","完美","合法");
        NM(RF("杂项", "移动", "Edge Jump"),"边缘跳跃")
            RF("杂项", "移动", "边缘跳跃"):SetDescription("按住热键时靠近边缘自动跳跃")
        NM(RF("杂项", "移动", "Slow Walk Key"),"慢走热键")
            RF("杂项", "移动", "慢走热键"):SetDescription("按住设定的热键时慢走生效")
        NM(RF("杂项", "移动", "Slow Walk Speed"),"慢走速度")
            RF("杂项", "移动", "慢走速度"):SetDescription("调整慢走速度, 目前过低走不动, 等修复")
        NM(RF("杂项", "移动", "Quick Stop"),"快速急停")
            RF("杂项", "移动", "快速急停"):SetDescription("松开移动键时快速急停, 无效等修复")

NM(RF("Configurations"),"参数")
    NM(RF("参数", "Local"),"本地")

NM(RF("Lua Scripts"),"Lua脚本")
    NM(RF("Lua脚本", "Local"),"本地")
    NM(RF("Lua脚本", "Security"),"安全")
        NM(RF("Lua脚本", "安全", "Allow scripts to edit lua files"),"允许脚本编辑lua文件")
            RF("Lua脚本", "安全", "允许脚本编辑lua文件"):SetDescription("允许修改其他脚本文件")
        NM(RF("Lua脚本", "安全", "Allow scripts to edit cfg files"),"允许脚本编辑cfg文件")
            RF("Lua脚本", "安全", "允许脚本编辑cfg文件"):SetDescription("允许修改本地参数文件")
        NM(RF("Lua脚本", "安全", "Allow internet connections"),"允许网络连接")
            RF("Lua脚本", "安全", "允许网络连接"):SetDescription("会泄露IP地址")
        NM(RF("Lua脚本", "安全", "Allow game scripting"),"允许游戏脚本")
            RF("Lua脚本", "安全", "允许游戏脚本"):SetDescription("可被滥用于通过 Steam API 编写恶意代码")
        NM(RF("Lua脚本", "安全", "Allow insecure FFI"),"允许不安全的FFI")
            RF("Lua脚本", "安全", "允许不安全的FFI"):SetDescription("可被滥用于恶意软件或恶意脚本")
        NM(RF("Lua脚本", "安全", "Save Lua Permissions"),"保存Lua权限")
            RF("Lua脚本", "安全", "保存Lua权限"):SetDescription("保存上述权限设置")
    NM(RF("Lua脚本", "Other"),"其它")
        NM(RF("Lua脚本", "其它", "Load With Configurations"),"随参数加载")
            RF("Lua脚本", "其它", "随参数加载"):SetDescription("开启后在脚本加载时保存参数, 下次注入后自动加载脚本")

print("更新日期: 2025-11-25")
print("汉化已加载, 请勿重复加载脚本")

function Something() end

callbacks.Register("Draw", Something)
