-- AimWare V6 For CS2 汉化
-- 旨在方便小白上手, 翻译可能不符合高手之间的叫法, 但大体意思是对的
-- 人工校对, 描述为个人理解, 可能不够准确, 欢迎指正

-- 启用控制台日志
gui.SetValue("misc.master", true);
gui.SetValue("misc.log.console", true);

WeaponList={"Shared",--全局共享
            "Zeus",--电击枪
            "Pistol",--手枪
            "Heavy Pistol",--沙鹰和左轮
            "Submachine Gun",--冲锋枪
            "Rifle",--步枪
            "Shotgun",--霰弹枪
            "Scout",--SSG08
            "Auto Sniper",--连狙
            "Sniper",--AWP
            "Light Machine Gun"--机枪
            }

RF=gui.Reference

function SN(RF,Name)
    RF:SetName(Name)
end

function SO(RF, ...)
    RF:SetOptions(...)
end

function SD(RF,Description)
    RF:SetDescription(Description)
end

function NN(RF, Name)
    for child in RF:Children() do
        if child:GetName() == Name then
            return child
        end

        local found = NN(child, Name)
        if found then
            return found
        end
    end
end

local function HasNonASCII(str)
    for i = 1, #str do
        local byteVal = string.byte(str, i)
        if byteVal > 127 then
            return true
        end
    end
    return false
end

local function CheckForNonASCII()
    local function CheckChildren(obj)
        local name = obj:GetName()
        if HasNonASCII(name) then
            print("加载被阻止 (简易防崩溃)")
            return true
        end
        for child in obj:Children() do
            if CheckChildren(child) then
                return true
            end
        end
        return false
    end
    return CheckChildren(gui.Reference("MENU"))
end

if CheckForNonASCII() then
    return
end

SN(RF("Legitbot"), "合法")
    SN(RF("合法", "Aimbot"), "自瞄")
        SN(RF("合法", "自瞄", "Main"), "主要")
            SN(RF("合法", "自瞄", "主要", "Enable"), "总开关")
                SD(RF("合法", "自瞄", "主要", "总开关"), "启用自瞄")
            SN(RF("合法", "自瞄", "主要", "Aim Key"), "自瞄热键")
                SD(RF("合法", "自瞄", "主要", "自瞄热键"), "按住热键时启用自瞄")
            SN(RF("合法", "自瞄", "主要", "Auto Pistol Interval"), "手枪连发间隔")
                SD(RF("合法", "自瞄", "主要", "手枪连发间隔"), "值不为0时, 长按开火键手枪连发, 间隔时间单位为毫秒")
        SN(RF("合法", "自瞄", "Hitbox Selection"), "自瞄部位选择")
            for i = 1, 11, 1 do
                SN(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Hitbox Advance Multiplier"), "部位切换增速")
                    SD(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "部位切换增速"), "部位切换额外增速")
                SN(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Nearest To Crosshair"), "准星附近优先")
                    SD(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "准星附近优先"), "首选准星最近部位, 然后按照优先级选择")
            end
    SN(RF("合法", "Triggerbot"), "扳机")
        SN(RF("合法", "扳机", "Main"), "主要")
            SN(RF("合法", "扳机", "主要", "Enable"), "总开关")
                SD(RF("合法", "扳机", "主要", "总开关"), "启用扳机")
            SN(RF("合法", "扳机", "主要", "Trigger Key"), "扳机热键")
                SD(RF("合法", "扳机", "主要", "扳机热键"), "按住热键时启用扳机")
            SN(RF("合法", "扳机", "主要", "Auto Fire"), "自动开火")
                SD(RF("合法", "扳机", "主要", "自动开火"), "启用时扳机常开, 不需要按住热键")
            SN(RF("合法", "扳机", "主要", "Knife Triggerbot"), "自动刀")
                SD(RF("合法", "扳机", "主要", "自动刀"), "自动按最优决策出刀, 不受总开关影响")
        SN(RF("合法", "扳机", "Weapon"), "武器")
            for i = 1, 11, 1 do
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Delay"), "扳机延迟")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "扳机延迟"), "时间单位为毫秒")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Burst"), "扳机连发时间")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "扳机连发时间"), "值不为0时, 扳机触发后连发, 时间单位为毫秒")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Hit Chance"), "最低命中率")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "最低命中率"), "命中率大于等于该值时才开火")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Accuracy"), "提高命中率")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "提高命中率"), "启用可提高命中率")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "提高命中率", "Anti-Recoil"), "考虑后坐")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "提高命中率", "Anti-Spread"), "扩散预测")
            end
        SN(RF("合法", "扳机", "Hitboxes"), "部位")
    SN(RF("合法", "Weapon"), "武器")
        SN(RF("合法", "武器", "Accuracy"), "压枪")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "压枪", WeaponList[i], "Recoil Control System"), "压枪时机")
                    SD(RF("合法", "武器", "压枪", WeaponList[i], "压枪时机"), "选择何时压枪")
                    SO(RF("合法", "武器", "压枪", WeaponList[i], "压枪时机"), "始终关闭", "自瞄时", "开火时")
                SN(RF("合法", "武器", "压枪", WeaponList[i], "Horizontal Recoil"), "水平压枪")
                    SD(RF("合法", "武器", "压枪", WeaponList[i], "水平压枪"), "抵消水平后坐")
                SN(RF("合法", "武器", "压枪", WeaponList[i], "Vertical Recoil"), "垂直压枪")
                    SD(RF("合法", "武器", "压枪", WeaponList[i], "垂直压枪"), "抵消垂直后坐")
            end
        SN(RF("合法", "武器", "Target"), "目标")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "目标", WeaponList[i], "Minimum FOV Range"), "最小范围")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "最小范围"), "准星在最小范围以内中断自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Maximum FOV Range"), "最大范围")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "最大范围"), "准星在最大范围以外中断自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Non-Sticky Target"), "超出最大范围中断自瞄")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "超出最大范围中断自瞄"), "启用后, 自瞄生效时, 目标超出最大范围中断自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Target Switch Delay"), "击杀后目标切换延迟")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "击杀后目标切换延迟"), "造成击杀后自瞄切换目标前的等待时间, 时间单位为毫秒")
                SN(RF("合法", "武器", "目标", WeaponList[i], "First Shot Delay"), "首发开火延迟")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "首发开火延迟"), "首发开火前的等待时间, 时间单位为毫秒")
            end
        SN(RF("合法", "武器", "Aiming"), "自瞄")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "自瞄", WeaponList[i], "Smooth Factor"), "平滑系数")
                    SD(RF("合法", "武器", "自瞄", WeaponList[i], "平滑系数"), "使自瞄更平滑, 越大越慢")
                SN(RF("合法", "武器", "自瞄", WeaponList[i], "Smooth Method"), "平滑模式")
                    SD(RF("合法", "武器", "自瞄", WeaponList[i], "平滑模式"), "自瞄的平滑模式")
                    SO(RF("合法", "武器", "自瞄", WeaponList[i], "平滑模式"), "动态", "静态")
                SN(RF("合法", "武器", "自瞄", WeaponList[i], "Randomize Factor"), "随机因子")
                    SD(RF("合法", "武器", "自瞄", WeaponList[i], "随机因子"), "调整自瞄至部位后的随机抖动程度")
                SN(RF("合法", "武器", "自瞄", WeaponList[i], "Curve Factor"), "曲线因子")
                    SD(RF("合法", "武器", "自瞄", WeaponList[i], "曲线因子"), "调整自瞄轨迹的非线性程度")
            end
        SN(RF("合法", "武器", "Visibility"), "可见性")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "可见性", WeaponList[i], "Auto Wall"), "穿墙")
                    SD(RF("合法", "武器", "可见性", WeaponList[i], "穿墙"), "自瞄与扳机穿墙")
                SN(RF("合法", "武器", "可见性", WeaponList[i], "Through Smoke"), "穿烟")
                    SD(RF("合法", "武器", "可见性", WeaponList[i], "穿烟"), "自瞄与扳机穿烟")
            end

SN(RF("Ragebot"), "暴力")
    SN(RF("暴力", "Main"), "主要")
        SN(RF("暴力", "主要", "Enabled"), "总开关")
            SD(RF("暴力", "主要", "总开关"), "启用无平滑自瞄(自动开火)")
        SN(RF("暴力", "主要", "Silent Aim"), "静默自瞄")
            SD(RF("暴力", "主要", "静默自瞄"), "自瞄不会更改你的视角")
        SN(RF("暴力", "主要", "Backtrack"), "射击回溯")
            SD(RF("暴力", "主要", "射击回溯"), "击中敌人之前的位置也造成伤害")
        SN(RF("暴力", "主要", "Anti-Recoil"), "无后坐")
            SD(RF("暴力", "主要", "无后坐"), "抵消武器后坐")
        SN(RF("暴力", "主要", "Anti-Spread"), "无扩散")
            SD(RF("暴力", "主要", "无扩散"), "移除武器扩散")
        SN(RF("暴力", "主要", "Double-Tap"), "双发速射")
            SD(RF("暴力", "主要", "双发速射"), "充能后短时间射出两发, 不受总开关影响")
        SN(RF("暴力", "主要", "Target Selection"), "目标优先级")
            SD(RF("暴力", "主要", "目标优先级"), "选择多目标时的目标优先级")
            SO(RF("暴力", "主要", "目标优先级"), "最低血量", "距离最近", "离准星最近")
        SN(RF("暴力", "主要", "FOV"), "范围")
            SD(RF("暴力", "主要", "范围"), "自瞄的最大范围, 范围以外不自瞄")
        SN(RF("暴力", "主要", "Knifebot"), "自动刀")
            SD(RF("暴力", "主要", "自动刀"), "自动刀模式, 不受总开关影响")
            SO(RF("暴力", "主要", "自动刀"), "关闭", "重击", "仅背刺", "快速")
        SN(RF("暴力", "主要", "Duck Peek assist"), "蹲起Peek")
            SD(RF("暴力", "主要", "蹲起Peek"), "按住蹲下, 若站起时可造成的伤害大于最低伤害, 则自动站起 (自动急停关闭时生效)")
        SN(RF("暴力", "主要", "Anti-aim Correction"), "假俯仰修正")
            SD(RF("暴力", "主要", "假俯仰修正"), "修正敌方反自瞄的假俯仰角度, 使自瞄正确击中头部")
    SN(RF("暴力", "Anti-Aim"), "反自瞄")
        SN(RF("暴力", "反自瞄", "Enabled"), "总开关")
            SD(RF("暴力", "反自瞄", "总开关"), "启用反自瞄")
        SN(RF("暴力", "反自瞄", "Pitch Angle"), "俯仰角度")
            SD(RF("暴力", "反自瞄", "俯仰角度"), "无需描述")
            SO(RF("暴力", "反自瞄", "俯仰角度"), "关闭", "低头", "抬头", "假抬头", "平视")
        SN(RF("暴力", "反自瞄", "Yaw Angle"), "偏航角度")
            SD(RF("暴力", "反自瞄", "偏航角度"), "无需描述")
            SO(RF("暴力", "反自瞄", "偏航角度"), "朝前", "朝后")
        SN(RF("暴力", "反自瞄", "Auto Direction"), "自动朝向")
            SD(RF("暴力", "反自瞄", "自动朝向"), "无需描述")
            SN(RF("暴力", "反自瞄", "自动朝向", "At Edges"), "墙边藏头")
            SN(RF("暴力", "反自瞄", "自动朝向", "At Targets"), "朝向目标")
        SN(RF("暴力", "反自瞄", "Disable Conditions"), "禁用时机")
            SD(RF("暴力", "反自瞄", "禁用时机"), "无需描述")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Use"), "交互时")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Knife"), "持刀时")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Grenade"), "持道具时")
            SN(RF("暴力", "反自瞄", "禁用时机", "During Freeze Time"), "回合冻结时")
    SN(RF("暴力", "Auto Peek"), "自动Peek")
        SN(RF("暴力", "自动Peek", "Enable"), "总开关")
            SD(RF("暴力", "自动Peek", "总开关"), "启用自动Peek")
                SN(NN(RF("暴力", "自动Peek", "总开关"), "Key"), "热键")
                    SD(NN(RF("暴力", "自动Peek", "总开关"), "热键"), "设定启用自动Peek的热键")
                SN(NN(RF("暴力", "自动Peek", "总开关"), "Show indicator"), "显示指示器")
                    SD(NN(RF("暴力", "自动Peek", "总开关"), "显示指示器"), "激活自动Peek后在脚底显示指示器")
                SN(NN(RF("暴力", "自动Peek", "总开关"), "Type"), "热键模式")
                    SD(NN(RF("暴力", "自动Peek", "总开关"), "热键模式"), "选择热键的工作模式")
                    SO(NN(RF("暴力", "自动Peek", "总开关"), "热键模式"), "按住生效", "开关切换")
                SN(NN(RF("暴力", "自动Peek", "总开关"), "Maintain Origin"), "复位不重置")
                    SD(NN(RF("暴力", "自动Peek", "总开关"), "复位不重置"), "开启后, 复位不清除状态, 可连续Peek, 无需关闭再开启")
    SN(RF("暴力", "Accuracy"), "数值")
        for i = 1, 11, 1 do
            SN(RF("暴力", "数值", WeaponList[i], "Min Damage"), "最低伤害")
                SD(RF("暴力", "数值", WeaponList[i], "最低伤害"), "可造成伤害大于等于该值时才开火。自适应伤害开启状态下, 穿墙时可致命自动降低最低伤害, 暴露时自动降低最低伤害至当前武器能造成的最高伤害, 避免过高最低伤害值导致不开枪")
            SN(RF("暴力", "数值", WeaponList[i], "Min Damage Options"), "其它")
                SD(RF("暴力", "数值", WeaponList[i], "其它"), "无需描述")
                SN(RF("暴力", "数值", WeaponList[i], "其它", "Auto Wall"), "穿墙")
                SN(RF("暴力", "数值", WeaponList[i], "其它", "Adaptive Damage"), "自适应伤害")
            SN(RF("暴力", "数值", WeaponList[i], "Hit Chance"), "最低命中率")
                SD(RF("暴力", "数值", WeaponList[i], "最低命中率"), "命中率大于等于该值时才开火")
        end
    SN(RF("暴力", "Hitbox"), "部位")
        for i = 1, 11, 1 do
            SN(RF("暴力", "部位", WeaponList[i], "Head"), "头部")
                SD(RF("暴力", "部位", WeaponList[i], "头部"), "无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Priority"), "优先攻击")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Exposed"), "暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Center"), "攻击部位中心")
            SN(RF("暴力", "部位", WeaponList[i], "Body"), "身体")
                SD(RF("暴力", "部位", WeaponList[i], "身体"), "无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Priority"), "优先攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Lethal"), "致命时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Exposed"), "暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Center"), "攻击部位中心")
            SN(RF("暴力", "部位", WeaponList[i], "Limbs"), "四肢")
                SD(RF("暴力", "部位", WeaponList[i], "四肢"), "无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "四肢", "Exposed"), "暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "四肢", "Center"), "攻击部位中心")
        end
    SN(RF("暴力", "Automate"), "自动")
        -- All (Auto Stop)
        for i = 1, 11, 1 do
            SN(RF("暴力", "自动", WeaponList[i], "Auto Stop"), "提高命中率")
                SD(RF("暴力", "自动", WeaponList[i], "提高命中率"), "无需描述")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Stop"), "自动急停")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Slow Walk"), "自动慢走")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Duck"), "射击前蹲下")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Between Shots"), "射击间隔急停")
        end

        -- Shared
        SN(RF("暴力", "自动", "Shared", "Auto Fire"), "单发武器选项")
            SD(RF("暴力", "自动", "Shared", "单发武器选项"), "无需描述")
            SN(RF("暴力", "自动", "Shared", "单发武器选项", "Auto Pistol"), "长按开火时连续开火")
            SN(RF("暴力", "自动", "Shared", "单发武器选项", "Auto Revolver"), "左轮自动预热")
        SN(RF("暴力", "自动", "Shared", "Auto Scope"), "狙击枪选项")
            SD(RF("暴力", "自动", "Shared", "狙击枪选项"), "无需描述")
            SN(RF("暴力", "自动", "Shared", "狙击枪选项", "Scope"), "自动开镜")
            SN(RF("暴力", "自动", "Shared", "狙击枪选项", "Unscope"), "自动关镜")
        -- Pistol
        SN(RF("暴力", "自动", "Pistol", "Auto Fire"), "单发武器选项")
            SD(RF("暴力", "自动", "Pistol", "单发武器选项"), "无需描述")
            SN(RF("暴力", "自动", "Pistol", "单发武器选项", "Auto Pistol"), "长按开火时连续开火")
        -- Heavy Pistol
        SN(RF("暴力", "自动", "Heavy Pistol", "Auto Fire"), "单发武器选项")
            SD(RF("暴力", "自动", "Heavy Pistol", "单发武器选项"), "无需描述")
            SN(RF("暴力", "自动", "Heavy Pistol", "单发武器选项", "Auto Pistol"), "长按开火时连续开火")
            SN(RF("暴力", "自动", "Heavy Pistol", "单发武器选项", "Auto Revolver"), "左轮自动预热")
        -- Scout
        SN(RF("暴力", "自动", "Scout", "Auto Fire"), "单发武器选项")
            SD(RF("暴力", "自动", "Scout", "单发武器选项"), "无需描述")
            SN(RF("暴力", "自动", "Scout", "单发武器选项", "Auto Pistol"), "长按开火时连续开火")
        SN(RF("暴力", "自动", "Scout", "Auto Scope"), "狙击枪选项")
            SD(RF("暴力", "自动", "Scout", "狙击枪选项"), "无需描述")
            SN(RF("暴力", "自动", "Scout", "狙击枪选项", "Scope"), "自动开镜")
            SN(RF("暴力", "自动", "Scout", "狙击枪选项", "Unscope"), "自动关镜")
        -- Auto Sniper
        SN(RF("暴力", "自动", "Auto Sniper", "Auto Scope"), "狙击枪选项")
            SD(RF("暴力", "自动", "Auto Sniper", "狙击枪选项"), "无需描述")
            SN(RF("暴力", "自动", "Auto Sniper", "狙击枪选项", "Scope"), "自动开镜")
            SN(RF("暴力", "自动", "Auto Sniper", "狙击枪选项", "Unscope"), "自动关镜")
        -- Sniper
        SN(RF("暴力", "自动", "Sniper", "Auto Fire"), "单发武器选项")
            SD(RF("暴力", "自动", "Sniper", "单发武器选项"), "无需描述")
            SN(RF("暴力", "自动", "Sniper", "单发武器选项", "Auto Pistol"), "长按开火时连续开火")
        SN(RF("暴力", "自动", "Sniper", "Auto Scope"), "狙击枪选项")
            SD(RF("暴力", "自动", "Sniper", "狙击枪选项"), "无需描述")
            SN(RF("暴力", "自动", "Sniper", "狙击枪选项", "Scope"), "自动开镜")
            SN(RF("暴力", "自动", "Sniper", "狙击枪选项", "Unscope"), "自动关镜")

SN(RF("Visuals"), "透视")
    SN(RF("透视", "Enemy"), "敌人")
        SN(RF("透视", "敌人", "Overlay"), "绘制")
            SN(RF("透视", "敌人", "绘制", "Box"), "方框")
                SN(RF("透视", "敌人", "绘制", "方框", "Style"), "样式")
                    SO(RF("透视", "敌人", "绘制", "方框", "样式"), "粗线", "细线")
                SN(RF("透视", "敌人", "绘制", "方框", "Precision"), "精确贴合")
                SN(RF("透视", "敌人", "绘制", "方框", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Ammo"), "弹药")
                SN(RF("透视", "敌人", "绘制", "弹药", "Ammo Full Color"), "满弹药颜色")
                SN(RF("透视", "敌人", "绘制", "弹药", "Ammo Empty Color"), "空弹药颜色")
            SN(RF("透视", "敌人", "绘制", "Health"), "血量")
                SN(RF("透视", "敌人", "绘制", "血量", "Health Bar"), "血量条")
                    SN(RF("透视", "敌人", "绘制", "血量", "血量条", "Health Max Color"), "满血颜色")
                    SN(RF("透视", "敌人", "绘制", "血量", "血量条", "Health Low Color"), "低血量颜色")
                SN(RF("透视", "敌人", "绘制", "血量", "Health Number"), "血量数值")
            SN(RF("透视", "敌人", "绘制", "Name"), "名字")
                SN(RF("透视", "敌人", "绘制", "名字", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Skeleton"), "骨骼")
                SN(RF("透视", "敌人", "绘制", "骨骼", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Armor"), "护甲")
                SN(RF("透视", "敌人", "绘制", "护甲", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Money"), "金钱")
                SN(RF("透视", "敌人", "绘制", "金钱", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Ping"), "延迟")
                SN(RF("透视", "敌人", "绘制", "延迟", "Color"), "颜色")
            SN(RF("透视", "敌人", "绘制", "Flags"), "状态")
                SN(RF("透视", "敌人", "绘制", "状态", "Defusing"), "拆弹中")
                SN(RF("透视", "敌人", "绘制", "状态", "Planting"), "安包中")
                SN(RF("透视", "敌人", "绘制", "状态", "Scoped"), "开镜中")
                SN(RF("透视", "敌人", "绘制", "状态", "Reloading"), "换弹中")
                SN(RF("透视", "敌人", "绘制", "状态", "Pin Pulled"), "已拉环")
                SN(RF("透视", "敌人", "绘制", "状态", "Flashed"), "被闪中")
                SN(RF("透视", "敌人", "绘制", "状态", "Has Defuser"), "有钳子")
                SN(RF("透视", "敌人", "绘制", "状态", "Has C4"), "带包")
            SN(RF("透视", "敌人", "绘制", "Barrel"), "视线")
                SN(RF("透视", "敌人", "绘制", "视线", "Start"), "起始渐变色")
                SN(RF("透视", "敌人", "绘制", "视线", "End"), "结束渐变色")
            SN(RF("透视", "敌人", "绘制", "Weapon"), "武器")
                SN(RF("透视", "敌人", "绘制", "武器", "Style"), "样式")
                    SO(RF("透视", "敌人", "绘制", "武器", "样式"), "图标", "名称")
                SN(RF("透视", "敌人", "绘制", "武器", "Filter"), "过滤")
                    SN(RF("透视", "敌人", "绘制", "武器", "过滤", "Active"), "手持")
                    SN(RF("透视", "敌人", "绘制", "武器", "过滤", "Inventory"), "背包")
                    SN(RF("透视", "敌人", "绘制", "武器", "过滤", "Nades"), "投掷物")
                SN(RF("透视", "敌人", "绘制", "武器", "Color"), "颜色")
                SN(RF("透视", "敌人", "绘制", "武器", "Important Color"), "重要信息颜色")
        SN(RF("透视", "敌人", "Chams"), "上色")
            SN(RF("透视", "敌人", "上色", "Model Visible"), "可见模型")
                SO(RF("透视", "敌人", "上色", "可见模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "敌人", "上色", "Model Occluded"), "被遮挡模型")
                SO(RF("透视", "敌人", "上色", "被遮挡模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "敌人", "上色", "Model Glow"), "模型边缘发光")
                SO(RF("透视", "敌人", "上色", "模型边缘发光"), "关闭", "开启")
            SN(RF("透视", "敌人", "上色", "Attachments Visible"), "可见武器")
                SO(RF("透视", "敌人", "上色", "可见武器"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "敌人", "上色", "Attachments Occluded"), "被遮挡武器")
                SO(RF("透视", "敌人", "上色", "被遮挡武器"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "敌人", "上色", "Ragdoll Visible"), "可见尸体")
                SO(RF("透视", "敌人", "上色", "可见尸体"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "敌人", "上色", "Ragdoll Occluded"), "被遮挡尸体")
                SO(RF("透视", "敌人", "上色", "被遮挡尸体"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
    SN(RF("透视", "Team"), "队友")
        SN(RF("透视", "队友", "Overlay"), "绘制")
            SN(RF("透视", "队友", "绘制", "Box"), "方框")
                SN(RF("透视", "队友", "绘制", "方框", "Style"), "样式")
                    SO(RF("透视", "队友", "绘制", "方框", "样式"), "粗线", "细线")
                SN(RF("透视", "队友", "绘制", "方框", "Precision"), "精确模式")
                SN(RF("透视", "队友", "绘制", "方框", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Ammo"), "弹药")
                SN(RF("透视", "队友", "绘制", "弹药", "Ammo Full Color"), "满弹药颜色")
                SN(RF("透视", "队友", "绘制", "弹药", "Ammo Empty Color"), "空弹药颜色")
            SN(RF("透视", "队友", "绘制", "Health"), "血量")
                SN(RF("透视", "队友", "绘制", "血量", "Health Bar"), "血量条")
                    SN(RF("透视", "队友", "绘制", "血量", "血量条", "Health Max Color"), "满血量颜色")
                    SN(RF("透视", "队友", "绘制", "血量", "血量条", "Health Low Color"), "低血量颜色")
                SN(RF("透视", "队友", "绘制", "血量", "Health Number"), "血量数值")
            SN(RF("透视", "队友", "绘制", "Name"), "名字")
                SN(RF("透视", "队友", "绘制", "名字", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Skeleton"), "骨骼")
                SN(RF("透视", "队友", "绘制", "骨骼", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Armor"), "护甲")
                SN(RF("透视", "队友", "绘制", "护甲", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Money"), "金钱")
                SN(RF("透视", "队友", "绘制", "金钱", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Ping"), "延迟")
                SN(RF("透视", "队友", "绘制", "延迟", "Color"), "颜色")
            SN(RF("透视", "队友", "绘制", "Flags"), "状态")
                SN(RF("透视", "队友", "绘制", "状态", "Defusing"), "拆弹中")
                SN(RF("透视", "队友", "绘制", "状态", "Planting"), "安包中")
                SN(RF("透视", "队友", "绘制", "状态", "Scoped"), "开镜中")
                SN(RF("透视", "队友", "绘制", "状态", "Reloading"), "换弹中")
                SN(RF("透视", "队友", "绘制", "状态", "Pin Pulled"), "已拉环")
                SN(RF("透视", "队友", "绘制", "状态", "Flashed"), "被闪中")
                SN(RF("透视", "队友", "绘制", "状态", "Has Defuser"), "有钳子")
                SN(RF("透视", "队友", "绘制", "状态", "Has C4"), "带包")
            SN(RF("透视", "队友", "绘制", "Barrel"), "视线")
                SN(RF("透视", "队友", "绘制", "视线", "Start"), "起始渐变色")
                SN(RF("透视", "队友", "绘制", "视线", "End"), "结束渐变色")
            SN(RF("透视", "队友", "绘制", "Weapon"), "武器")
                SN(RF("透视", "队友", "绘制", "武器", "Style"), "样式")
                    SO(RF("透视", "队友", "绘制", "武器", "样式"), "图标", "名称")
                SN(RF("透视", "队友", "绘制", "武器", "Filter"), "过滤")
                    SN(RF("透视", "队友", "绘制", "武器", "过滤", "Active"), "手持")
                    SN(RF("透视", "队友", "绘制", "武器", "过滤", "Inventory"), "背包")
                    SN(RF("透视", "队友", "绘制", "武器", "过滤", "Nades"), "投掷物")
                SN(RF("透视", "队友", "绘制", "武器", "Color"), "颜色")
                SN(RF("透视", "队友", "绘制", "武器", "Important Color"), "重要信息颜色")
        SN(RF("透视", "队友", "Chams"), "上色")
            SN(RF("透视", "队友", "上色", "Model Visible"), "可见模型")
                SO(RF("透视", "队友", "上色", "可见模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "队友", "上色", "Model Occluded"), "被遮挡模型")
                SO(RF("透视", "队友", "上色", "被遮挡模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "队友", "上色", "Model Glow"), "模型边缘发光")
                SO(RF("透视", "队友", "上色", "模型边缘发光"), "关闭", "开启")
            SN(RF("透视", "队友", "上色", "Attachments Visible"), "可见武器")
                SO(RF("透视", "队友", "上色", "可见武器"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "队友", "上色", "Attachments Occluded"), "被遮挡武器")
                SO(RF("透视", "队友", "上色", "被遮挡武器"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "队友", "上色", "Ragdoll Visible"), "可见尸体")
                SO(RF("透视", "队友", "上色", "可见尸体"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "队友", "上色", "Ragdoll Occluded"), "被遮挡尸体")
                SO(RF("透视", "队友", "上色", "被遮挡尸体"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
    SN(RF("透视", "Weapon"), "武器")
        SN(RF("透视", "武器", "Overlay"), "绘制")
            SN(RF("透视", "武器", "绘制", "Box"), "方框")
                SN(RF("透视", "武器", "绘制", "方框", "Style"), "样式")
                    SO(RF("透视", "武器", "绘制", "方框", "样式"), "粗线", "细线")
                SN(RF("透视", "武器", "绘制", "方框", "Precision"), "精确模式")
                SN(RF("透视", "武器", "绘制", "方框", "Color"), "颜色")
            SN(RF("透视", "武器", "绘制", "Ammo"), "弹药")
                SN(RF("透视", "武器", "绘制", "弹药", "Ammo Full Color"), "满弹药颜色")
                SN(RF("透视", "武器", "绘制", "弹药", "Ammo Empty Color"), "空弹药颜色")
            SN(RF("透视", "武器", "绘制", "Name"), "名字")
                SN(RF("透视", "武器", "绘制", "名字", "Style"), "样式")
                    SO(RF("透视", "武器", "绘制", "名字", "样式"), "图标", "名称")
                SN(RF("透视", "武器", "绘制", "名字", "Color"), "颜色")
            SN(RF("透视", "武器", "绘制", "Nades"), "投掷物")
                SN(RF("透视", "武器", "绘制", "投掷物", "Name"), "名称")
                SN(RF("透视", "武器", "绘制", "投掷物", "Icon"), "图标")
                SN(RF("透视", "武器", "绘制", "投掷物", "Detonate Timer"), "引爆计时器")
            SN(RF("透视", "武器", "绘制", "C4 Timer"), "C4计时")
            SN(RF("透视", "武器", "绘制", "Defuser"), "钳子")
        SN(RF("透视", "武器", "Chams"), "上色")
            SN(RF("透视", "武器", "上色", "Model Visible"), "可见模型")
                SO(RF("透视", "武器", "上色", "可见模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "武器", "上色", "Model Occluded"), "被遮挡模型")
                SO(RF("透视", "武器", "上色", "被遮挡模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "武器", "上色", "Model Glow"), "模型边缘发光")
                SO(RF("透视", "武器", "上色", "模型边缘发光"), "关闭", "开启")
    SN(RF("透视", "Local"), "自身")
        SN(RF("透视", "自身", "Chams"), "上色")
            SN(RF("透视", "自身", "上色", "Model Visible"), "可见模型")
                SO(RF("透视", "自身", "上色", "可见模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "自身", "上色", "Model Occluded"), "被遮挡模型")
                SO(RF("透视", "自身", "上色", "被遮挡模型"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "自身", "上色", "Attachments Visible"), "可见武器(第三人称)")
                SO(RF("透视", "自身", "上色", "可见武器(第三人称)"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "自身", "上色", "Attachments Occluded"), "被遮挡武器(第三人称)")
                SO(RF("透视", "自身", "上色", "被遮挡武器(第三人称)"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "自身", "上色", "Weapon Visible"), "可见武器(第一人称)")
                SO(RF("透视", "自身", "上色", "可见武器(第一人称)"), "关闭", "平面", "纹理", "发光", "塑料", "金属")
            SN(RF("透视", "自身", "上色", "Arms Visible"), "可见手臂(第一人称)")
                SO(RF("透视", "自身", "上色", "可见手臂(第一人称)"), "关闭", "平面", "纹理", "发光", "塑料", "金属")

SN(RF("World"), "视觉")
    SN(RF("视觉", "Camera"), "相机")
        SN(RF("视觉", "相机", "Third Person Enable"), "第三人称开关")
            SD(RF("视觉", "相机", "第三人称开关"), "开关第三人称视角")
        SN(RF("视觉", "相机", "Third Person Distance"), "第三人称距离")
            SD(RF("视觉", "相机", "第三人称距离"), "调整视角距离")
        SN(RF("视觉", "相机", "View FOV"), "视野范围")
            SD(RF("视觉", "相机", "视野范围"), "调整视野范围")
        SN(RF("视觉", "相机", "Viewmodel FOV"), "模型范围")
            SD(RF("视觉", "相机", "模型范围"), "调整武器模型视野范围")
    SN(RF("视觉", "Ambience"), "环境")
        SN(RF("视觉", "环境", "Apply on Main Menu"), "主菜单生效")
            SD(RF("视觉", "环境", "主菜单生效"), "颜色调整在主菜单也生效")
        SN(RF("视觉", "环境", "Weather"), "天气")
            SO(RF("视觉", "环境", "天气"), "无", "雨天", "雪天", "余烬", "灰烬")
            for i = 1, 4 do
                SN(NN(RF("视觉", "环境", "天气"), "Color Override"), "颜色")
                    SD(NN(RF("视觉", "环境", "天气"), "颜色"), "调整天气特效颜色")
                SN(NN(RF("视觉", "环境", "天气"), "Intensity"), "强度")
                    SD(NN(RF("视觉", "环境", "天气"), "强度"), "调整特效数量")
                
            end

            for i = 1, 3 do
                SN(NN(RF("视觉", "环境", "天气"), "Glow"), "边缘发光")
                    SD(NN(RF("视觉", "环境", "天气"), "边缘发光"), "特效边缘发光")
            end

            for i = 1, 2 do
                SN(NN(RF("视觉", "环境", "天气"), "Lightning"), "雷电")
                    SD(NN(RF("视觉", "环境", "天气"), "雷电"), "开关雷电和雷声")
            end
        SN(RF("视觉", "环境", "Skybox"), "天空")
            SD(RF("视觉", "环境", "天空"), "选择天空盒预设, 或使用自定义天空盒")
        SN(RF("视觉", "环境", "World Color"), "地图颜色")
            SD(RF("视觉", "环境", "地图颜色"), "调整地图颜色")
        SN(RF("视觉", "环境", "Sky Color"), "天空颜色")
            SD(RF("视觉", "环境", "天空颜色"), "调整天空颜色")
        SN(RF("视觉", "环境", "Clouds Color"), "云朵颜色")
            SD(RF("视觉", "环境", "云朵颜色"), "调整云朵颜色")
        SN(RF("视觉", "环境", "Sun Color"), "太阳颜色")
            SD(RF("视觉", "环境", "太阳颜色"), "调整太阳颜色")
        SN(RF("视觉", "环境", "Explosion Color"), "爆炸颜色")
            SD(RF("视觉", "环境", "爆炸颜色"), "调整爆炸特效颜色")
        SN(RF("视觉", "环境", "Fire Color"), "火焰颜色")
            SD(RF("视觉", "环境", "火焰颜色"), "调整火焰特效颜色")
        SN(RF("视觉", "环境", "Muzzle Flash Color"), "枪口火光颜色")
            SD(RF("视觉", "环境", "枪口火光颜色"), "调整枪口火光颜色")
        SN(RF("视觉", "环境", "Smoke Color"), "烟雾颜色")
            SD(RF("视觉", "环境", "烟雾颜色"), "调整烟雾颜色")
    SN(RF("视觉", "Extra"), "增强")
        SN(RF("视觉", "增强", "Radar"), "雷达")
            SD(RF("视觉", "增强", "雷达"), "游戏地图显示敌人位置")
        SN(RF("视觉", "增强", "Visualize Aimbot"), "显示可击中部位")
            SD(RF("视觉", "增强", "显示可击中部位"), "显示敌人可造成伤害的部位")
        SN(RF("视觉", "增强", "Sniper Crosshair"), "狙击枪准星")
            SD(RF("视觉", "增强", "狙击枪准星"), "显示狙击枪准星")
        SN(RF("视觉", "增强", "Crosshair Recoil"), "可视扩散")
            SD(RF("视觉", "增强", "可视扩散"), "显示扩散范围")
            SO(RF("视觉", "增强", "可视扩散"), "关闭", "圆环1", "渐变", "圆环2")
        SN(RF("视觉", "增强", "Effects Removal"), "特效移除")
            SD(RF("视觉", "增强", "特效移除"), "移除视觉特效")
            SN(RF("视觉", "增强", "特效移除", "No Flash"), "闪光")
            SN(RF("视觉", "增强", "特效移除", "No Smoke"), "烟雾")
            SN(RF("视觉", "增强", "特效移除", "No Recoil"), "视觉后坐")
            SN(RF("视觉", "增强", "特效移除", "No Scope"), "瞄准镜放大")
            SN(RF("视觉", "增强", "特效移除", "No Scope Overlay"), "瞄准镜虚化")
            SN(RF("视觉", "增强", "特效移除", "No Sky"), "天空")
    SN(RF("视觉", "Helper"), "辅助")
        SN(RF("视觉", "辅助", "Wallbang Info"), "穿墙指示器")
            SD(RF("视觉", "辅助", "穿墙指示器"), "显示穿墙信息")
            SN(RF("视觉", "辅助", "穿墙指示器", "Damage"), "伤害")
            SN(RF("视觉", "辅助", "穿墙指示器", "Circle"), "圆圈")
            SN(RF("视觉", "辅助", "穿墙指示器", "Crosshair"), "准星")
        SN(RF("视觉", "辅助", "Out Of View"), "视野外指示器")
            SD(RF("视觉", "辅助", "视野外指示器"), "显示视野外敌人方位")
            SO(RF("视觉", "辅助", "视野外指示器"), "关闭", "箭头", "箭头+详细信息")
        SN(RF("视觉", "辅助", "Out Of View Scale"), "指示器距离")
            SD(RF("视觉", "辅助", "指示器距离"), "调整指示器离准星的距离")
        SN(RF("视觉", "辅助", "Indicators"), "指示器")
            SD(RF("视觉", "辅助", "指示器"), "显示状态")
            SN(RF("视觉", "辅助", "指示器", "Double-Tap"), "双发速射")
            SN(RF("视觉", "辅助", "指示器", "Anti Spread"), "扩散预测与无扩散")
            SN(RF("视觉", "辅助", "指示器", "Min Damage"), "最低伤害")
        SN(RF("视觉", "辅助", "Inferno"), "显示燃烧弹范围")
            SD(RF("视觉", "辅助", "显示燃烧弹范围"), "燃烧弹蔓延范围")
            SN(RF("视觉", "辅助", "显示燃烧弹范围", "Local"), "自身")
            SN(RF("视觉", "辅助", "显示燃烧弹范围", "Friendly"), "友军")
            SN(RF("视觉", "辅助", "显示燃烧弹范围", "Enemy"), "敌人")
        SN(RF("视觉", "辅助", "Smoke"), "显示烟雾范围")
            SD(RF("视觉", "辅助", "显示烟雾范围"), "显示烟雾蔓延范围")
        SN(RF("视觉", "辅助", "Grenade Tracer"), "显示手雷轨迹")
            SD(RF("视觉", "辅助", "显示手雷轨迹"), "手雷空中轨迹")
            SN(RF("视觉", "辅助", "显示手雷轨迹", "Local"), "自身")
            SN(RF("视觉", "辅助", "显示手雷轨迹", "Friendly"), "友军")
            SN(RF("视觉", "辅助", "显示手雷轨迹", "Enemy"), "敌人")
            SN(RF("视觉", "辅助", "显示手雷轨迹", "Color Fade"), "颜色渐变")
        SN(RF("视觉", "辅助", "Grenade Warning"), "显示手雷警告")
            SD(RF("视觉", "辅助", "显示手雷警告"), "手雷落点警告")
            SN(RF("视觉", "辅助", "显示手雷警告", "Local"), "自身")
            SN(RF("视觉", "辅助", "显示手雷警告", "Friendly"), "友军")
            SN(RF("视觉", "辅助", "显示手雷警告", "Enemy"), "敌人")
        SN(RF("视觉", "辅助", "Hit Effects"), "显示命中特效")
            SD(RF("视觉", "辅助", "显示命中特效"), "命中敌人时的特效")
            SN(RF("视觉", "辅助", "显示命中特效", "Sound"), "声音")
            SN(RF("视觉", "辅助", "显示命中特效", "Marker"), "标记")
        SN(RF("视觉", "辅助", "Damage Indicator"), "伤害指示器开关")
            SD(RF("视觉", "辅助", "伤害指示器开关"), "命中后在敌人头顶显示伤害值")
        SN(RF("视觉", "辅助", "Kill Effect"), "击杀特效")
            SD(RF("视觉", "辅助", "击杀特效"), "击杀敌人后的特效")
            SO(RF("视觉", "辅助", "击杀特效"), "关闭", "汽化", "液化")
                SN(NN(RF("视觉", "辅助", "击杀特效"), "Primary Color"), "主要颜色")
                SN(NN(RF("视觉", "辅助", "击杀特效"), "Secondary Color"), "次要颜色")
                SN(NN(RF("视觉", "辅助", "击杀特效"), "Intensity"), "强度")
                SN(NN(RF("视觉", "辅助", "击杀特效"), "Dissolve"), "扩散")
        SN(RF("视觉", "辅助", "Bullet Tracers"), "显示子弹轨迹")
            SD(RF("视觉", "辅助", "显示子弹轨迹"), "显示子弹飞行轨迹")
            SN(RF("视觉", "辅助", "显示子弹轨迹", "Local"), "自身")
            SN(RF("视觉", "辅助", "显示子弹轨迹", "Friendly"), "友军")
            SN(RF("视觉", "辅助", "显示子弹轨迹", "Enemy"), "敌人")

SN(RF("Miscellaneous"), "杂项")
    SN(RF("杂项", "Features"), "功能")
        SN(RF("杂项", "功能", "Secure Mode"), "安全模式")
            SD(RF("杂项", "功能", "安全模式"), "限制部分功能, 降低封禁概率")
            SO(RF("杂项", "功能", "安全模式"), "严格", "开启", "关闭")
        SN(RF("杂项", "功能", "Chat Spam"), "广告")
            SD(RF("杂项", "功能", "广告"), "自动发送AW广告消息")
        SN(RF("杂项", "功能", "Auto-Accept Match"), "自动准备")
            SD(RF("杂项", "功能", "自动准备"), "自动最后准备比赛")
        SN(RF("杂项", "功能", "Preserve Killfeed"), "保留击杀信息")
            SD(RF("杂项", "功能", "保留击杀信息"), "不移除击杀信息")
        SN(RF("杂项", "功能", "Show Spectators"), "显示观战者")
            SD(RF("杂项", "功能", "显示观战者"), "显示观战你的玩家")
        SN(RF("杂项", "功能", "Anti-OBS"), "反OBS")
            SD(RF("杂项", "功能", "反OBS"), "使OBS录不到作弊画面, 只支持OBS游戏采集模式")
        SN(RF("杂项", "功能", "Show Watermark"), "显示水印")
            SD(RF("杂项", "功能", "显示水印"), "右上角显示水印")
        SN(RF("杂项", "功能", "Quick Plant"), "快速下包")
            SD(RF("杂项", "功能", "快速下包"), "快速切到C4")
        SN(RF("杂项", "功能", "Straight Throw"), "投掷偏移修正")
            SD(RF("杂项", "功能", "投掷偏移修正"), "修正移动时投掷偏移")
        SN(RF("杂项", "功能", "Log"), "日志")
            SD(RF("杂项", "功能", "日志"), "左上角显示日志信息")
            SN(RF("杂项", "功能", "日志", "Console"), "控制台")
            SN(RF("杂项", "功能", "日志", "Purchases"), "购买")
            SN(RF("杂项", "功能", "日志", "Damage"), "伤害")
    SN(RF("杂项", "Movement"), "移动")
        SN(RF("杂项", "移动", "Auto Strafe"), "空中加速")
            SD(RF("杂项", "移动", "空中加速"), "滞空时增加移速和灵活性")
                SN(NN(RF("杂项", "移动", "空中加速"), "Speed Boost"), "加速增幅")
                    SD(NN(RF("杂项", "移动", "空中加速"), "加速增幅"), "调整空中加速的增幅")
                SN(NN(RF("杂项", "移动", "空中加速"), "Air Turn Speed"), "转向速度增幅")
                    SD(NN(RF("杂项", "移动", "空中加速"), "转向速度增幅"), "调整空中转向的速度增幅")
        SN(RF("杂项", "移动", "Auto Jump"), "自动连跳")
            SD(RF("杂项", "移动", "自动连跳"), "选择自动连跳的模式")
            SO(RF("杂项", "移动", "自动连跳"), "关闭", "完美", "合法")
        SN(RF("杂项", "移动", "Jump Bug"), "跳跃漏洞")
            SD(RF("杂项", "移动", "跳跃漏洞"), "选择阻止落地惩罚的时机")
            SO(RF("杂项", "移动", "跳跃漏洞"), "关闭", "常开", "坠落受伤时")
        SN(RF("杂项", "移动", "Edge Jump"), "边缘跳跃")
            SD(RF("杂项", "移动", "边缘跳跃"), "按住热键时走到边缘自动跳跃")
        SN(RF("杂项", "移动", "Air Duck"), "空中蹲下")
            SD(RF("杂项", "移动", "空中蹲下"), "空中自动蹲下")
        SN(RF("杂项", "移动", "Slow Walk Key"), "慢走热键")
            SD(RF("杂项", "移动", "慢走热键"), "按住设定的热键时慢走生效")
        SN(RF("杂项", "移动", "Slow Walk Speed"), "慢走速度")
            SD(RF("杂项", "移动", "慢走速度"), "按住热键时按设定百分比调整移速")
        SN(RF("杂项", "移动", "Fast Ladder"), "快速爬梯")
            SD(RF("杂项", "移动", "快速爬梯"), "加快爬梯速度")
        SN(RF("杂项", "移动", "Quick Stop"), "快速急停")
            SD(RF("杂项", "移动", "快速急停"), "松开移动键时快速急停")

SN(RF("Configurations"), "参数")
    SN(RF("参数", "Local"), "本地")
        SN(NN(RF("参数", "本地"), "Create"), "创建")

SN(RF("Lua Scripts"), "Lua脚本")
    SN(RF("Lua脚本", "Local"), "本地")
        SN(NN(RF("Lua脚本", "本地"), "Create"), "创建")
    SN(RF("Lua脚本", "Security"), "安全")
        SN(RF("Lua脚本", "安全", "Allow scripts to edit lua files"), "允许脚本编辑lua文件")
            SD(RF("Lua脚本", "安全", "允许脚本编辑lua文件"), "允许修改其他脚本文件")
        SN(RF("Lua脚本", "安全", "Allow scripts to edit cfg files"), "允许脚本编辑cfg文件")
            SD(RF("Lua脚本", "安全", "允许脚本编辑cfg文件"), "允许修改本地参数文件")
        SN(RF("Lua脚本", "安全", "Allow internet connections"), "允许网络连接")
            SD(RF("Lua脚本", "安全", "允许网络连接"), "会泄露IP地址")
        SN(RF("Lua脚本", "安全", "Allow game scripting"), "允许游戏脚本")
            SD(RF("Lua脚本", "安全", "允许游戏脚本"), "可被滥用于通过 Steam API 编写恶意代码")
        SN(RF("Lua脚本", "安全", "Allow insecure FFI"), "允许不安全的FFI")
            SD(RF("Lua脚本", "安全", "允许不安全的FFI"), "可被滥用于恶意软件或恶意脚本")
        SN(RF("Lua脚本", "安全", "Save Lua Permissions"), "保存Lua权限")
            SD(RF("Lua脚本", "安全", "保存Lua权限"), "保存Lua权限设置")
    SN(RF("Lua脚本", "Other"), "其它")
        SN(RF("Lua脚本", "其它", "Load With Configurations"), "随参数加载")
            SD(RF("Lua脚本", "其它", "随参数加载"), "开启后在脚本加载时保存参数, 加载参数时自动加载脚本")

SN(NN(RF("MENU"), "Dpi Scale"), "界面缩放比例")
    SD(NN(RF("MENU"), "界面缩放比例"), "调整界面缩放比例, 以适应不同分辨率")
    SO(NN(RF("MENU"), "界面缩放比例"), "75%",
                                    "100% (默认)",
                                    "125%",
                                    "150%",
                                    "175%",
                                    "200%",
                                    "225%",
                                    "250%",
                                    "275%",
                                    "300%")
SN(NN(RF("MENU"), "Theme"), "主题")
    SD(NN(RF("MENU"), "主题"), "选择预设配色主题")
    SO(NN(RF("MENU"), "主题"), "默认", "浅色", "深色")
SN(NN(RF("MENU"), "Menu Key"), "菜单热键")
    SD(NN(RF("MENU"), "菜单热键"), "设置开关菜单热键")
SN(NN(RF("MENU"), "Console Key"), "控制台热键")
    SD(NN(RF("MENU"), "控制台热键"), "设置开关控制台热键")
SN(NN(RF("MENU"), "Show Binds"), "显示绑定状态")
    SD(NN(RF("MENU"), "显示绑定状态"), "在新的界面 (可拖动) 显示绑定了按键的功能的状态 (开关/选项/数值)")
    SO(NN(RF("MENU"), "显示绑定状态"), "关闭", "变量", "名称", "短名")
SN(NN(RF("MENU"), "Show UI Hints"), "显示功能描述")
    SD(NN(RF("MENU"), "显示功能描述"), "指针悬停在功能名上时显示描述")
SN(NN(RF("MENU"), "UI Opacity"), "界面透明度")
    SD(NN(RF("MENU"), "界面透明度"), "调整界面透明度")

print("更新日期: 2026-04-09")
print("汉化已加载")

-- 使脚本一直处于加载状态, 允许保存为随参数加载
function Something() end
callbacks.Register("Draw", Something)
