WeaponList={"Shared","Zeus","Pistol","Heavy Pistol","Submachine Gun","Rifle","Shotgun","Scout","Auto Sniper","Sniper","Light Machine Gun"}

RF=gui.Reference

function SN(RF,Name)
    RF:SetName(Name)
end

function SO(RF, ...)
    RF:SetOptions(...)
end

function SD(RF,Description)
    RF:SetDescription(Description)
end

function NN(RF, Name)
    for child in RF:Children() do
        if child:GetName() == Name then
            return child
        end

        local found = NN(child, Name)
        if found then
            return found
        end
    end
end

local function HasNonASCII(str)
    for i = 1, #str do
        local byteVal = string.byte(str, i)
        if byteVal > 127 then
            return true
        end
    end
    return false
end

local function CheckForNonASCII()
    local function CheckChildren(obj)
        local name = obj:GetName()
        if HasNonASCII(name) then
            print("跳过加载")
            return true
        end
        for child in obj:Children() do
            if CheckChildren(child) then
                return true
            end
        end
        return false
    end
    return CheckChildren(gui.Reference("MENU"))
end

if CheckForNonASCII() then
    return
end

SN(RF("Legitbot"),"合法")
    SN(RF("合法", "Aimbot"),"自瞄")
        SN(RF("合法", "自瞄", "Main"),"主要")
            SN(RF("合法", "自瞄", "主要", "Enable"),"自瞄开关")
                SD(RF("合法", "自瞄", "主要", "自瞄开关"),"启用自瞄")
            SN(RF("合法", "自瞄", "主要", "Aim Key"),"自瞄热键")
                SD(RF("合法", "自瞄", "主要", "自瞄热键"),"按住热键时启用自瞄")
            SN(RF("合法", "自瞄", "主要", "Auto Pistol Interval"),"手枪连发间隔")
                SD(RF("合法", "自瞄", "主要", "手枪连发间隔"),"值不为0时, 长按开火键手枪连发, 间隔时间单位为毫秒")
        SN(RF("合法", "自瞄", "Hitbox Selection"),"自瞄部位选择")
            for i = 1, 11, 1 do
                SN(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Hitbox Advance Multiplier"),"自瞄部位切换速度")
                    SD(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "自瞄部位切换速度"),"数值越大越快")
                SN(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "Nearest To Crosshair"),"准星附近优先")
                    SD(RF("合法", "自瞄", "自瞄部位选择", WeaponList[i], "准星附近优先"),"首选准星最近部位")
            end
    SN(RF("合法", "Triggerbot"),"扳机")
        SN(RF("合法", "扳机", "Main"),"主要")
            SN(RF("合法", "扳机", "主要", "Enable"),"扳机开关")
                SD(RF("合法", "扳机", "主要", "扳机开关"),"启用扳机")
            SN(RF("合法", "扳机", "主要", "Trigger Key"),"扳机热键")
                SD(RF("合法", "扳机", "主要", "扳机热键"),"按住热键时启用扳机")
            SN(RF("合法", "扳机", "主要", "Auto Fire"),"自动开火")
                SD(RF("合法", "扳机", "主要", "自动开火"),"启用时扳机常开, 不需要按住热键")
            SN(RF("合法", "扳机", "主要", "Knife Triggerbot"),"自动刀")
                SD(RF("合法", "扳机", "主要", "自动刀"),"未开启扳机开关时, 启用此功能仍然生效")
        SN(RF("合法", "扳机", "Weapon"),"武器")
            for i = 1, 11, 1 do
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Delay"),"扳机延迟")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "扳机延迟"),"时间单位为毫秒")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Trigger Burst"),"扳机连发时间")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "扳机连发时间"),"值不为0时, 扳机触发后连发, 时间单位为毫秒")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Hit Chance"),"最低命中率")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "最低命中率"),"超过设定值才开火")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "Accuracy"),"精度提升")
                    SD(RF("合法", "扳机", "武器", WeaponList[i], "精度提升"),"启用后提高扳机精度")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "精度提升", "Anti-Recoil"),"考虑后坐")
                SN(RF("合法", "扳机", "武器", WeaponList[i], "精度提升", "Anti-Spread"),"扩散预测")
            end
        SN(RF("合法", "扳机", "Hitboxes"),"部位")
    SN(RF("合法", "Weapon"),"武器")
        SN(RF("合法", "武器", "Accuracy"),"压枪")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器","压枪", WeaponList[i], "Recoil Control System"),"压枪时机")
                    SD(RF("合法", "武器","压枪", WeaponList[i], "压枪时机"),"选择何时压枪")
                    SO(RF("合法", "武器","压枪", WeaponList[i], "压枪时机"),"始终关闭","自瞄时","开火时")
                SN(RF("合法", "武器","压枪", WeaponList[i], "Horizontal Recoil"),"水平压枪")
                    SD(RF("合法", "武器","压枪", WeaponList[i], "水平压枪"),"抵消水平后坐")
                SN(RF("合法", "武器","压枪", WeaponList[i], "Vertical Recoil"),"垂直压枪")
                    SD(RF("合法", "武器","压枪", WeaponList[i], "垂直压枪"),"抵消垂直后坐")
            end
        SN(RF("合法", "武器", "Target"),"目标")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "目标", WeaponList[i], "Minimum FOV Range"),"最小范围")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "最小范围"),"最小范围以内不自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Maximum FOV Range"),"最大范围")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "最大范围"),"最大范围以外不自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Non-Sticky Target"),"超出最大范围停止自瞄")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "超出最大范围停止自瞄"),"目标超出最大范围后停止自瞄")
                SN(RF("合法", "武器", "目标", WeaponList[i], "Target Switch Delay"),"击杀后目标切换延迟")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "击杀后目标切换延迟"),"造成击杀后自瞄切换目标前的等待时间, 时间单位为毫秒")
                SN(RF("合法", "武器", "目标", WeaponList[i], "First Shot Delay"),"首发开火延迟")
                    SD(RF("合法", "武器", "目标", WeaponList[i], "首发开火延迟"),"首发开火前的等待时间, 时间单位为毫秒")
            end
        SN(RF("合法", "武器", "Aiming"),"瞄准")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Factor"),"平滑系数")
                    SD(RF("合法", "武器", "瞄准", WeaponList[i], "平滑系数"),"使自瞄更平滑, 越大越慢")
                SN(RF("合法", "武器", "瞄准", WeaponList[i], "Smooth Method"),"平滑模式")
                    SD(RF("合法", "武器", "瞄准", WeaponList[i], "平滑模式"),"自瞄的平滑模式")
                    SO(RF("合法", "武器", "瞄准", WeaponList[i], "平滑模式"),"动态","静态")
                SN(RF("合法", "武器", "瞄准", WeaponList[i], "Randomize Factor"),"随机因子")
                    SD(RF("合法", "武器", "瞄准", WeaponList[i], "随机因子"),"值不为0时增加自瞄的随机性")
                SN(RF("合法", "武器", "瞄准", WeaponList[i], "Curve Factor"),"曲线因子")
                    SD(RF("合法", "武器", "瞄准", WeaponList[i], "曲线因子"),"自瞄的非线性程度")
            end
        SN(RF("合法", "武器", "Visibility"),"可见性")
            for i = 1, 11, 1 do
                SN(RF("合法", "武器", "可见性", WeaponList[i], "Auto Wall"),"穿墙")
                    SD(RF("合法", "武器", "可见性", WeaponList[i], "穿墙"),"自瞄与扳机穿墙")
                SN(RF("合法", "武器", "可见性", WeaponList[i], "Through Smoke"),"穿烟")
                    SD(RF("合法", "武器", "可见性", WeaponList[i], "穿烟"),"自瞄与扳机穿烟")
            end

SN(RF("Ragebot"),"暴力")
    SN(RF("暴力", "Main"),"主要")
        SN(RF("暴力", "主要", "Enabled"),"总开关")
            SD(RF("暴力", "主要", "总开关"),"启用自瞄和自动开火")
        SN(RF("暴力", "主要", "Silent Aim"),"静默自瞄")
            SD(RF("暴力", "主要", "静默自瞄"),"自瞄不会更改你的视角")
        SN(RF("暴力", "主要", "Backtrack"),"射击回溯")
            SD(RF("暴力", "主要", "射击回溯"),"击中敌人之前的位置也造成伤害")
        SN(RF("暴力", "主要", "Anti-Recoil"),"无后坐")
            SD(RF("暴力", "主要", "无后坐"),"抵消武器后坐")
        SN(RF("暴力", "主要", "Anti-Spread"),"无扩散")
            SD(RF("暴力", "主要", "无扩散"),"抵消武器扩散")
        SN(RF("暴力", "主要", "Double-Tap"),"双发速射")
            SD(RF("暴力", "主要", "双发速射"),"充能后短时间打出两发, 不受总开关影响")
        SN(RF("暴力", "主要", "Target Selection"),"目标优先级")
            SD(RF("暴力", "主要", "目标优先级"),"多目标时优先选择目标的方式")
            SO(RF("暴力", "主要", "目标优先级"),"最低血量", "距离最近", "离准星最近")
        SN(RF("暴力", "主要", "FOV"),"范围")
            SD(RF("暴力", "主要", "范围"),"自瞄的最大范围, 范围以外不自瞄")
        SN(RF("暴力", "主要", "Knifebot"),"自动刀")
            SD(RF("暴力", "主要", "自动刀"),"自动刀模式, 不受总开关影响")
            SO(RF("暴力", "主要", "自动刀"),"关闭","重击","仅背刺","快速")
        SN(RF("暴力", "主要", "Duck Peek assist"),"蹲起Peek")
            SD(RF("暴力", "主要", "蹲起Peek"),"按住蹲下, 如果站起时可对目标造成的伤害大于设定的最小值, 则自动站起")
        SN(RF("暴力", "主要", "Anti-aim Correction"),"假角度修正")
            SD(RF("暴力", "主要", "假角度修正"),"修正敌方反自瞄的假俯仰角度, 使自瞄正确击中头部")
    SN(RF("暴力", "Anti-Aim"),"反自瞄")
        SN(RF("暴力", "反自瞄", "Enabled"),"总开关")
            SD(RF("暴力", "反自瞄", "总开关"),"启用反自瞄")
        SN(RF("暴力", "反自瞄", "Pitch Angle"),"俯仰角度")
            SD(RF("暴力", "反自瞄", "俯仰角度"),"无需描述")
            SO(RF("暴力", "反自瞄", "俯仰角度"),"关闭","低头","抬头","假抬头","平视")
        SN(RF("暴力", "反自瞄", "Yaw Angle"),"偏航角度")
            SD(RF("暴力", "反自瞄", "偏航角度"),"无需描述")
            SO(RF("暴力", "反自瞄", "偏航角度"),"朝前","朝后")
        SN(RF("暴力", "反自瞄", "Auto Direction"),"自动朝向")
            SD(RF("暴力", "反自瞄", "自动朝向"),"无需描述")
            SN(RF("暴力", "反自瞄", "自动朝向", "At Edges"),"墙边藏头")
            SN(RF("暴力", "反自瞄", "自动朝向", "At Targets"),"朝向目标")
        SN(RF("暴力", "反自瞄", "Disable Conditions"),"禁用时机")
            SD(RF("暴力", "反自瞄", "禁用时机"),"无需描述")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Use"),"交互时")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Knife"),"持刀时")
            SN(RF("暴力", "反自瞄", "禁用时机", "On Grenade"),"持道具时")
            SN(RF("暴力", "反自瞄", "禁用时机", "During Freeze Time"),"回合冻结时")
    SN(RF("暴力", "Auto Peek"),"自动Peek")
        SN(RF("暴力", "自动Peek", "Enable"),"总开关")
            SD(RF("暴力", "自动Peek", "总开关"),"启用自动Peek")
            SN(NN(RF("暴力", "自动Peek", "总开关"), "Key"),"热键")
                SD(NN(RF("暴力", "自动Peek", "总开关"), "热键"),"设定启用自动Peek的热键")
            SN(NN(RF("暴力", "自动Peek", "总开关"), "Show indicator"),"渲染指示器")
                SD(NN(RF("暴力", "自动Peek", "总开关"), "渲染指示器"),"激活自动Peek后在脚底渲染指示器")
        SN(NN(RF("暴力", "自动Peek", "总开关"), "Type"),"热键模式")
            SD(NN(RF("暴力", "自动Peek", "总开关"), "热键模式"),"选择热键的工作模式")
            SO(NN(RF("暴力", "自动Peek", "总开关"), "热键模式"),"按住生效","开关切换")
        SN(NN(RF("暴力", "自动Peek", "总开关"), "Maintain Origin"),"复位不重置")
            SD(NN(RF("暴力", "自动Peek", "总开关"), "复位不重置"),"开启后, 复位不清除状态, 可连续Peek, 无需关闭再开启")
    SN(RF("暴力", "Accuracy"),"数值")
        for i = 1, 11, 1 do
            SN(RF("暴力", "数值", WeaponList[i], "Min Damage"),"最低伤害")
                SD(RF("暴力", "数值", WeaponList[i], "最低伤害"),"可造成伤害大于等于该值时才开火。自适应伤害开启状态下, 穿墙时可致命自动降低最低伤害, 暴露时自动降低最低伤害至当前武器能造成的最高伤害, 避免过高最小伤害值导致不开枪")
            SN(RF("暴力", "数值", WeaponList[i], "Min Damage Options"),"其它")
                SN(RF("暴力", "数值", WeaponList[i], "其它", "Auto Wall"),"穿墙")
                SN(RF("暴力", "数值", WeaponList[i], "其它", "Adaptive Damage"),"自适应伤害")
            SN(RF("暴力", "数值", WeaponList[i], "Hit Chance"),"最低命中率")
                SD(RF("暴力", "数值", WeaponList[i], "最低命中率"),"命中率大于等于该值时才开火")
        end
    SN(RF("暴力", "Hitbox"),"部位")
        for i = 1, 11, 1 do
            SN(RF("暴力", "部位", WeaponList[i], "Head"),"头部")
                SD(RF("暴力", "部位", WeaponList[i], "头部"),"无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Priority"),"优先攻击")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Exposed"),"暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "头部", "Center"),"攻击部位中心")
            SN(RF("暴力", "部位", WeaponList[i], "Body"),"身体")
                SD(RF("暴力", "部位", WeaponList[i], "身体"),"无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Priority"),"优先攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Lethal"),"致命时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Exposed"),"暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "身体", "Center"),"攻击部位中心")
            SN(RF("暴力", "部位", WeaponList[i], "Limbs"),"四肢")
                SD(RF("暴力", "部位", WeaponList[i], "四肢"),"无需描述")
            SN(RF("暴力", "部位", WeaponList[i], "四肢", "Exposed"),"暴露时攻击")
            SN(RF("暴力", "部位", WeaponList[i], "四肢", "Center"),"攻击部位中心")
        end
    SN(RF("暴力", "Automate"),"自动")
        -- All Weapon [Auto Stop]
        for i = 1, 11, 1 do
            SN(RF("暴力", "自动", WeaponList[i], "Auto Stop"),"提高命中率")
                SD(RF("暴力", "自动", WeaponList[i], "提高命中率"),"无需描述")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Stop"),"自动急停")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Slow Walk"),"自动慢走")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Duck"),"射击前蹲下")
                SN(RF("暴力", "自动", WeaponList[i], "提高命中率", "Between Shots"),"射击间隔急停")
        end
        -- Shared
        SN(RF("暴力", "自动", "Shared", "Auto Fire"),"单发武器选项")
            SD(RF("暴力", "自动", "Shared", "单发武器选项"),"无需描述")
            SN(RF("暴力", "自动", "Shared", "单发武器选项", "Auto Pistol"),"长按开火时连续开火")
            SN(RF("暴力", "自动", "Shared", "单发武器选项", "Auto Revolver"),"左轮自动预热")
        SN(RF("暴力", "自动", "Shared", "Auto Scope"),"狙击枪选项")
            SD(RF("暴力", "自动", "Shared", "狙击枪选项"),"无需描述")
            SN(RF("暴力", "自动", "Shared", "狙击枪选项", "Scope"),"自动开镜")
            SN(RF("暴力", "自动", "Shared", "狙击枪选项", "Unscope"),"自动关镜")
        -- Pistol
        SN(RF("暴力", "自动", "Pistol", "Auto Fire"),"单发武器选项")
            SD(RF("暴力", "自动", "Pistol", "单发武器选项"),"无需描述")
            SN(RF("暴力", "自动", "Pistol", "单发武器选项", "Auto Pistol"),"长按开火时连续开火")
        -- Heavy Pistol
        SN(RF("暴力", "自动", "Heavy Pistol", "Auto Fire"),"单发武器选项")
            SD(RF("暴力", "自动", "Heavy Pistol", "单发武器选项"),"无需描述")
            SN(RF("暴力", "自动", "Heavy Pistol", "单发武器选项", "Auto Pistol"),"长按开火时连续开火")
            SN(RF("暴力", "自动", "Heavy Pistol", "单发武器选项", "Auto Revolver"),"左轮自动预热")
        -- Scout
        SN(RF("暴力", "自动", "Scout", "Auto Fire"),"单发武器选项")
            SD(RF("暴力", "自动", "Scout", "单发武器选项"),"无需描述")
            SN(RF("暴力", "自动", "Scout", "单发武器选项", "Auto Pistol"),"长按开火时连续开火")
        SN(RF("暴力", "自动", "Scout", "Auto Scope"),"狙击枪选项")
            SD(RF("暴力", "自动", "Scout", "狙击枪选项"),"无需描述")
            SN(RF("暴力", "自动", "Scout", "狙击枪选项", "Scope"),"自动开镜")
            SN(RF("暴力", "自动", "Scout", "狙击枪选项", "Unscope"),"自动关镜")
        -- Auto Sniper
        SN(RF("暴力", "自动", "Auto Sniper", "Auto Scope"),"狙击枪选项")
            SD(RF("暴力", "自动", "Auto Sniper", "狙击枪选项"),"无需描述")
            SN(RF("暴力", "自动", "Auto Sniper", "狙击枪选项", "Scope"),"自动开镜")
            SN(RF("暴力", "自动", "Auto Sniper", "狙击枪选项", "Unscope"),"自动关镜")
        -- Sniper
        SN(RF("暴力", "自动", "Sniper", "Auto Fire"),"单发武器选项")
            SD(RF("暴力", "自动", "Sniper", "单发武器选项"),"无需描述")
            SN(RF("暴力", "自动", "Sniper", "单发武器选项", "Auto Pistol"),"长按开火时连续开火")
        SN(RF("暴力", "自动", "Sniper", "Auto Scope"),"狙击枪选项")
            SD(RF("暴力", "自动", "Sniper", "狙击枪选项"),"无需描述")
            SN(RF("暴力", "自动", "Sniper", "狙击枪选项", "Scope"),"自动开镜")
            SN(RF("暴力", "自动", "Sniper", "狙击枪选项", "Unscope"),"自动关镜")

SN(RF("Visuals"),"视觉")
    SN(RF("视觉", "Enemy"),"敌人")
        SN(RF("视觉", "敌人", "Overlay"),"绘制")
            SN(RF("视觉", "敌人", "绘制", "Box"),"方框")
                SN(RF("视觉", "敌人", "绘制", "方框", "Style"),"样式")
                    SO(RF("视觉", "敌人", "绘制", "方框", "样式"),"粗线","细线")
                SN(RF("视觉", "敌人", "绘制", "方框", "Precision"),"精确贴合")
                SN(RF("视觉", "敌人", "绘制", "方框", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Ammo"),"弹药")
                SN(RF("视觉", "敌人", "绘制", "弹药", "Ammo Full Color"),"满弹药颜色")
                SN(RF("视觉", "敌人", "绘制", "弹药", "Ammo Empty Color"),"空弹药颜色")
            SN(RF("视觉", "敌人", "绘制", "Health"),"血量")
                SN(RF("视觉", "敌人", "绘制", "血量", "Health Bar"),"血量条")
                    SN(RF("视觉", "敌人", "绘制", "血量", "血量条", "Health Max Color"),"满血颜色")
                    SN(RF("视觉", "敌人", "绘制", "血量", "血量条", "Health Low Color"),"低血量颜色")
                SN(RF("视觉", "敌人", "绘制", "血量", "Health Number"),"血量数值")
            SN(RF("视觉", "敌人", "绘制", "Name"),"名字")
                SN(RF("视觉", "敌人", "绘制", "名字", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Skeleton"),"骨骼")
                SN(RF("视觉", "敌人", "绘制", "骨骼", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Armor"),"护甲")
                SN(RF("视觉", "敌人", "绘制", "护甲", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Money"),"金钱")
                SN(RF("视觉", "敌人", "绘制", "金钱", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Ping"),"延迟")
                SN(RF("视觉", "敌人", "绘制", "延迟", "Color"),"颜色")
            SN(RF("视觉", "敌人", "绘制", "Flags"),"状态")
                SN(RF("视觉", "敌人", "绘制", "状态", "Defusing"),"拆弹中")
                SN(RF("视觉", "敌人", "绘制", "状态", "Planting"),"安包中")
                SN(RF("视觉", "敌人", "绘制", "状态", "Scoped"),"开镜中")
                SN(RF("视觉", "敌人", "绘制", "状态", "Reloading"),"换弹中")
                SN(RF("视觉", "敌人", "绘制", "状态", "Pin Pulled"),"已拉环")
                SN(RF("视觉", "敌人", "绘制", "状态", "Flashed"),"被闪中")
                SN(RF("视觉", "敌人", "绘制", "状态", "Has Defuser"),"有钳子")
                SN(RF("视觉", "敌人", "绘制", "状态", "Has C4"),"带包")
            SN(RF("视觉", "敌人", "绘制", "Barrel"),"视线")
                SN(RF("视觉", "敌人", "绘制", "视线", "Start"),"起始渐变色")
                SN(RF("视觉", "敌人", "绘制", "视线", "End"),"结束渐变色")
            SN(RF("视觉", "敌人", "绘制", "Weapon"),"武器")
                SN(RF("视觉", "敌人", "绘制", "武器", "Style"),"样式")
                    SO(RF("视觉", "敌人", "绘制", "武器", "样式"),"图标","名称")
                SN(RF("视觉", "敌人", "绘制", "武器", "Filter"),"过滤")
                    SN(RF("视觉", "敌人", "绘制", "武器", "过滤", "Active"),"手持")
                    SN(RF("视觉", "敌人", "绘制", "武器", "过滤", "Inventory"),"背包")
                    SN(RF("视觉", "敌人", "绘制", "武器", "过滤", "Nades"),"投掷物")
                SN(RF("视觉", "敌人", "绘制", "武器", "Color"),"颜色")
                SN(RF("视觉", "敌人", "绘制", "武器", "Important Color"),"重要信息颜色")
        SN(RF("视觉", "敌人", "Chams"),"上色")
            SN(RF("视觉", "敌人", "上色", "Model Visible"),"可见模型")
                SO(RF("视觉", "敌人", "上色", "可见模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "敌人", "上色", "Model Occluded"),"被遮挡模型")
                SO(RF("视觉", "敌人", "上色", "被遮挡模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "敌人", "上色", "Model Glow"),"模型边缘发光")
                SO(RF("视觉", "敌人", "上色", "模型边缘发光"),"关闭","开启")
            SN(RF("视觉", "敌人", "上色", "Attachments Visible"),"可见武器")
                SO(RF("视觉", "敌人", "上色", "可见武器"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "敌人", "上色", "Attachments Occluded"),"被遮挡武器")
                SO(RF("视觉", "敌人", "上色", "被遮挡武器"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "敌人", "上色", "Ragdoll Visible"),"可见尸体")
                SO(RF("视觉", "敌人", "上色", "可见尸体"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "敌人", "上色", "Ragdoll Occluded"),"被遮挡尸体")
                SO(RF("视觉", "敌人", "上色", "被遮挡尸体"),"关闭","平面","纹理","发光","塑料","金属")
    SN(RF("视觉", "Team"),"队友")
        SN(RF("视觉", "队友", "Overlay"),"绘制")
            SN(RF("视觉", "队友", "绘制", "Box"),"方框")
                SN(RF("视觉", "队友", "绘制", "方框", "Style"),"样式")
                    SO(RF("视觉", "队友", "绘制", "方框", "样式"),"粗线","细线")
                SN(RF("视觉", "队友", "绘制", "方框", "Precision"),"精确模式")
                SN(RF("视觉", "队友", "绘制", "方框", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Ammo"),"弹药")
                SN(RF("视觉", "队友", "绘制", "弹药", "Ammo Full Color"),"满弹药颜色")
                SN(RF("视觉", "队友", "绘制", "弹药", "Ammo Empty Color"),"空弹药颜色")
            SN(RF("视觉", "队友", "绘制", "Health"),"血量")
                SN(RF("视觉", "队友", "绘制", "血量", "Health Bar"),"血量条")
                    SN(RF("视觉", "队友", "绘制", "血量", "血量条", "Health Max Color"),"满血量颜色")
                    SN(RF("视觉", "队友", "绘制", "血量", "血量条", "Health Low Color"),"低血量颜色")
                SN(RF("视觉", "队友", "绘制", "血量", "Health Number"),"血量数值")
            SN(RF("视觉", "队友", "绘制", "Name"),"名字")
                SN(RF("视觉", "队友", "绘制", "名字", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Skeleton"),"骨骼")
                SN(RF("视觉", "队友", "绘制", "骨骼", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Armor"),"护甲")
                SN(RF("视觉", "队友", "绘制", "护甲", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Money"),"金钱")
                SN(RF("视觉", "队友", "绘制", "金钱", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Ping"),"延迟")
                SN(RF("视觉", "队友", "绘制", "延迟", "Color"),"颜色")
            SN(RF("视觉", "队友", "绘制", "Flags"),"状态")
                SN(RF("视觉", "队友", "绘制", "状态", "Defusing"),"拆弹中")
                SN(RF("视觉", "队友", "绘制", "状态", "Planting"),"安包中")
                SN(RF("视觉", "队友", "绘制", "状态", "Scoped"),"开镜中")
                SN(RF("视觉", "队友", "绘制", "状态", "Reloading"),"换弹中")
                SN(RF("视觉", "队友", "绘制", "状态", "Pin Pulled"),"已拉环")
                SN(RF("视觉", "队友", "绘制", "状态", "Flashed"),"被闪中")
                SN(RF("视觉", "队友", "绘制", "状态", "Has Defuser"),"有钳子")
                SN(RF("视觉", "队友", "绘制", "状态", "Has C4"),"带包")
            SN(RF("视觉", "队友", "绘制", "Barrel"),"视线")
                SN(RF("视觉", "队友", "绘制", "视线", "Start"),"起始渐变色")
                SN(RF("视觉", "队友", "绘制", "视线", "End"),"结束渐变色")
            SN(RF("视觉", "队友", "绘制", "Weapon"),"武器")
                SN(RF("视觉", "队友", "绘制", "武器", "Style"),"样式")
                    SO(RF("视觉", "队友", "绘制", "武器", "样式"),"图标","名称")
                SN(RF("视觉", "队友", "绘制", "武器", "Filter"),"过滤")
                    SN(RF("视觉", "队友", "绘制", "武器", "过滤", "Active"),"手持")
                    SN(RF("视觉", "队友", "绘制", "武器", "过滤", "Inventory"),"背包")
                    SN(RF("视觉", "队友", "绘制", "武器", "过滤", "Nades"),"投掷物")
                SN(RF("视觉", "队友", "绘制", "武器", "Color"),"颜色")
                SN(RF("视觉", "队友", "绘制", "武器", "Important Color"),"重要信息颜色")
        SN(RF("视觉", "队友", "Chams"),"上色")
            SN(RF("视觉", "队友", "上色", "Model Visible"),"可见模型")
                SO(RF("视觉", "队友", "上色", "可见模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "队友", "上色", "Model Occluded"),"被遮挡模型")
                SO(RF("视觉", "队友", "上色", "被遮挡模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "队友", "上色", "Model Glow"),"模型边缘发光")
                SO(RF("视觉", "队友", "上色", "模型边缘发光"),"关闭","开启")
            SN(RF("视觉", "队友", "上色", "Attachments Visible"),"可见武器")
                SO(RF("视觉", "队友", "上色", "可见武器"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "队友", "上色", "Attachments Occluded"),"被遮挡武器")
                SO(RF("视觉", "队友", "上色", "被遮挡武器"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "队友", "上色", "Ragdoll Visible"),"可见尸体")
                SO(RF("视觉", "队友", "上色", "可见尸体"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "队友", "上色", "Ragdoll Occluded"),"被遮挡尸体")
                SO(RF("视觉", "队友", "上色", "被遮挡尸体"),"关闭","平面","纹理","发光","塑料","金属")
    SN(RF("视觉", "Weapon"),"武器")
        SN(RF("视觉", "武器", "Overlay"),"绘制")
            SN(RF("视觉", "武器", "绘制", "Box"),"方框")
                SN(RF("视觉", "武器", "绘制", "方框", "Style"),"样式")
                    SO(RF("视觉", "武器", "绘制", "方框", "样式"),"粗线","细线")
                SN(RF("视觉", "武器", "绘制", "方框", "Precision"),"精确模式")
                SN(RF("视觉", "武器", "绘制", "方框", "Color"),"颜色")
            SN(RF("视觉", "武器", "绘制", "Ammo"),"弹药")
                SN(RF("视觉", "武器", "绘制", "弹药", "Ammo Full Color"),"满弹药颜色")
                SN(RF("视觉", "武器", "绘制", "弹药", "Ammo Empty Color"),"空弹药颜色")
            SN(RF("视觉", "武器", "绘制", "Name"),"名字")
                SN(RF("视觉", "武器", "绘制", "名字", "Style"),"样式")
                    SO(RF("视觉", "武器", "绘制", "名字", "样式"),"图标","名称")
                SN(RF("视觉", "武器", "绘制", "名字", "Color"),"颜色")
            SN(RF("视觉", "武器", "绘制", "Nades"),"投掷物")
                SN(RF("视觉", "武器", "绘制", "投掷物", "Name"),"名称")
                SN(RF("视觉", "武器", "绘制", "投掷物", "Icon"),"图标")
                SN(RF("视觉", "武器", "绘制", "投掷物", "Detonate Timer"),"引爆计时器")
            SN(RF("视觉", "武器", "绘制", "C4 Timer"),"C4计时")
            SN(RF("视觉", "武器", "绘制", "Defuser"),"钳子")
        SN(RF("视觉", "武器", "Chams"),"上色")
            SN(RF("视觉", "武器", "上色", "Model Visible"),"可见模型")
                SO(RF("视觉", "武器", "上色", "可见模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "武器", "上色", "Model Occluded"),"被遮挡模型")
                SO(RF("视觉", "武器", "上色", "被遮挡模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "武器", "上色", "Model Glow"),"模型发光")
                SO(RF("视觉", "武器", "上色", "模型发光"),"关闭","开启")
    SN(RF("视觉", "Local"),"自身")
        SN(RF("视觉", "自身", "Chams"),"上色")
            SN(RF("视觉", "自身", "上色", "Model Visible"),"可见模型")
                SO(RF("视觉", "自身", "上色", "可见模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "自身", "上色", "Model Occluded"),"被遮挡模型")
                SO(RF("视觉", "自身", "上色", "被遮挡模型"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "自身", "上色", "Attachments Visible"),"可见武器(第三人称)")
                SO(RF("视觉", "自身", "上色", "可见武器(第三人称)"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "自身", "上色", "Attachments Occluded"),"被遮挡武器(第三人称)")
                SO(RF("视觉", "自身", "上色", "被遮挡武器(第三人称)"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "自身", "上色", "Weapon Visible"),"可见武器(第一人称)")
                SO(RF("视觉", "自身", "上色", "可见武器(第一人称)"),"关闭","平面","纹理","发光","塑料","金属")
            SN(RF("视觉", "自身", "上色", "Arms Visible"),"可见手臂(第一人称)")
                SO(RF("视觉", "自身", "上色", "可见手臂(第一人称)"),"关闭","平面","纹理","发光","塑料","金属")

print("预览版")
print("汉化已加载")

-- 使脚本一直处于加载状态
function Something() end

callbacks.Register("Draw", Something)
